import type { CountryConfig } from '../countries'

export const denmarkConfig: CountryConfig = {
  code: 'dk',
  name: 'Danmark',
  center: [56, 10],
  zoom: 7,
  selfSufficiency: 1.0,
  municipalityIdProp: 'kommunekode',
  municipalityNameProp: 'kommunenavn',
  chains: {
    netto: { id: 'netto', name: 'Netto', color: '#E31937', type: 'discount', parent: 'Salling Group' },
    'rema-1000': { id: 'rema-1000', name: 'Rema 1000', color: '#003DA5', type: 'discount', parent: 'Reitangruppen' },
    '365discount': { id: '365discount', name: '365discount', color: '#00529B', type: 'discount', parent: 'Coop Danmark' },
    'coop-365discount': { id: 'coop-365discount', name: 'Coop 365discount', color: '#00529B', type: 'discount', parent: 'Coop Danmark' },
    'coop-365-discount': { id: 'coop-365-discount', name: 'Coop 365 discount', color: '#00529B', type: 'discount', parent: 'Coop Danmark' },
    superbrugsen: { id: 'superbrugsen', name: 'SuperBrugsen', color: '#003D74', type: 'supermarket', parent: 'Coop Danmark' },
    'dagli-brugsen': { id: 'dagli-brugsen', name: "Dagli'Brugsen", color: '#00529B', type: 'convenience', parent: 'Coop Danmark' },
    daglibrugsen: { id: 'daglibrugsen', name: 'DagliBrugsen', color: '#00529B', type: 'convenience', parent: 'Coop Danmark' },
    brugsen: { id: 'brugsen', name: 'Brugsen', color: '#00529B', type: 'convenience', parent: 'Coop Danmark' },
    kvickly: { id: 'kvickly', name: 'Kvickly', color: '#003D74', type: 'supermarket', parent: 'Coop Danmark' },
    lidl: { id: 'lidl', name: 'Lidl', color: '#0050AA', type: 'discount', parent: 'Lidl' },
    'min-k-bmand': { id: 'min-k-bmand', name: 'Min Kobmand', color: '#2E8B57', type: 'convenience', parent: 'Dagrofa' },
    spar: { id: 'spar', name: 'Spar', color: '#228B22', type: 'convenience', parent: 'Dagrofa' },
    meny: { id: 'meny', name: 'Meny', color: '#3CB371', type: 'supermarket', parent: 'Dagrofa' },
    'f-tex': { id: 'f-tex', name: 'Fotex', color: '#C41430', type: 'supermarket', parent: 'Salling Group' },
    'f-tex-food': { id: 'f-tex-food', name: 'Fotex Food', color: '#C41430', type: 'supermarket', parent: 'Salling Group' },
    bilka: { id: 'bilka', name: 'Bilka', color: '#A01028', type: 'hypermarket', parent: 'Salling Group' },
    'abc-lavpris': { id: 'abc-lavpris', name: 'ABC Lavpris', color: '#2E8B57', type: 'discount', parent: 'Dagrofa' },
    'elite-k-bmand': { id: 'elite-k-bmand', name: 'Elite Kobmand', color: '#2E8B57', type: 'convenience', parent: 'Dagrofa' },
    'l-vbjerg': { id: 'l-vbjerg', name: 'Lovbjerg', color: '#2E8B57', type: 'supermarket', parent: 'Dagrofa' },
    'let-k-b': { id: 'let-k-b', name: 'Let-Kob', color: '#2E8B57', type: 'discount', parent: 'Dagrofa' },
    'letk-b': { id: 'letk-b', name: 'Letkob', color: '#2E8B57', type: 'discount', parent: 'Dagrofa' },
  },
  chainParents: {
    netto: 'Salling Group',
    'rema-1000': 'Reitangruppen',
    '365discount': 'Coop Danmark',
    'coop-365discount': 'Coop Danmark',
    'coop-365-discount': 'Coop Danmark',
    superbrugsen: 'Coop Danmark',
    'dagli-brugsen': 'Coop Danmark',
    daglibrugsen: 'Coop Danmark',
    brugsen: 'Coop Danmark',
    kvickly: 'Coop Danmark',
    lidl: 'Lidl',
    'min-k-bmand': 'Dagrofa',
    spar: 'Dagrofa',
    meny: 'Dagrofa',
    'f-tex': 'Salling Group',
    'f-tex-food': 'Salling Group',
    bilka: 'Salling Group',
    'abc-lavpris': 'Dagrofa',
    'elite-k-bmand': 'Dagrofa',
    'l-vbjerg': 'Dagrofa',
    'let-k-b': 'Dagrofa',
    'letk-b': 'Dagrofa',
  },
  parentColors: {
    'Salling Group': '#E31937',
    'Coop Danmark': '#00529B',
    Reitangruppen: '#003DA5',
    Dagrofa: '#2E8B57',
    Lidl: '#0050AA',
  },
  processingCompanies: [],
  dataFiles: {
    stores: 'stores.json',
    municipalities: 'municipalities.json',
    boundaries: 'municipalities.geojson',
  },
  dataSources: [
    {
      layer: 'Butikker',
      file: 'stores.json',
      records: '3 869 lokationer',
      source: 'OpenStreetMap (Overpass API)',
      sourceUrl: 'https://overpass-turbo.eu/',
      updated: '2024-Q4',
      limitations: 'OSM-daekning varierer efter region. Nogle butikker kan mangle eller vaere lukket. Kaedetilknytning baseret pa brand-tag.',
      reproduce: 'Overpass-foresporgsel: shop=supermarket og shop=convenience inden for Danmark',
    },
  ],
}
