import type { CountryConfig } from '../countries'

export const finlandConfig: CountryConfig = {
  code: 'fi',
  name: 'Finland',
  center: [64, 26],
  zoom: 5,
  selfSufficiency: 0.80,
  municipalityIdProp: 'kuntanumero',
  municipalityNameProp: 'kuntanimi',
  chains: {
    'k-market': { id: 'k-market', name: 'K-Market', color: '#FF6600', type: 'convenience', parent: 'Kesko' },
    'k-supermarket': { id: 'k-supermarket', name: 'K-Supermarket', color: '#CC5200', type: 'supermarket', parent: 'Kesko' },
    'k-citymarket': { id: 'k-citymarket', name: 'K-Citymarket', color: '#993D00', type: 'hypermarket', parent: 'Kesko' },
    's-market': { id: 's-market', name: 'S-market', color: '#00A651', type: 'supermarket', parent: 'S-Group' },
    sale: { id: 'sale', name: 'Sale', color: '#008C44', type: 'discount', parent: 'S-Group' },
    alepa: { id: 'alepa', name: 'Alepa', color: '#00A651', type: 'convenience', parent: 'S-Group' },
    prisma: { id: 'prisma', name: 'Prisma', color: '#006633', type: 'hypermarket', parent: 'S-Group' },
    lidl: { id: 'lidl', name: 'Lidl', color: '#0050AA', type: 'discount', parent: 'Lidl' },
    halpahalli: { id: 'halpahalli', name: 'HalpaHalli', color: '#E31937', type: 'discount', parent: 'Tokmanni Group' },
    minimani: { id: 'minimani', name: 'Minimani', color: '#6B7280', type: 'discount', parent: 'Minimani' },
  },
  chainParents: {
    'k-market': 'Kesko',
    'k-supermarket': 'Kesko',
    'k-citymarket': 'Kesko',
    's-market': 'S-Group',
    sale: 'S-Group',
    alepa: 'S-Group',
    prisma: 'S-Group',
    lidl: 'Lidl',
    halpahalli: 'Tokmanni Group',
    minimani: 'Minimani',
  },
  parentColors: {
    'S-Group': '#00A651',
    Kesko: '#FF6600',
    Lidl: '#0050AA',
    'Tokmanni Group': '#E31937',
    Minimani: '#6B7280',
  },
  processingCompanies: [],
  dataFiles: {
    stores: 'stores.json',
    municipalities: 'municipalities.json',
    boundaries: 'municipalities.geojson',
  },
  dataSources: [
    {
      layer: 'Kaupat',
      file: 'stores.json',
      records: '2 860 sijaintia',
      source: 'OpenStreetMap (Overpass API)',
      sourceUrl: 'https://overpass-turbo.eu/',
      updated: '2024-Q4',
      limitations: 'OSM-kattavuus vaihtelee alueittain. Jotkut kaupat voivat puuttua tai olla lopetettu. Ketjutunnistus perustuu brand-tagiin.',
      reproduce: 'Overpass-kysely: shop=supermarket ja shop=convenience Suomen alueella',
    },
  ],
}
