import type { CountryConfig } from '../countries'

export const norwayConfig: CountryConfig = {
  code: 'no',
  name: 'Norge',
  center: [65, 13],
  zoom: 5,
  selfSufficiency: 0.45,
  municipalityIdProp: 'kommunenummer',
  municipalityNameProp: 'kommunenavn',
  chains: {
    rema: { id: 'rema', name: 'Rema 1000', color: '#E30613', type: 'discount', parent: 'Reitangruppen' },
    kiwi: { id: 'kiwi', name: 'Kiwi', color: '#4CAF50', type: 'discount', parent: 'NorgesGruppen' },
    extra: { id: 'extra', name: 'Extra', color: '#FFC107', type: 'discount', parent: 'Coop Norge' },
    'coop-prix': { id: 'coop-prix', name: 'Coop Prix', color: '#00529B', type: 'discount', parent: 'Coop Norge' },
    bunnpris: { id: 'bunnpris', name: 'Bunnpris', color: '#E91E63', type: 'discount', parent: 'Bunnpris AS' },
    joker: { id: 'joker', name: 'Joker', color: '#F44336', type: 'convenience', parent: 'NorgesGruppen' },
    spar: { id: 'spar', name: 'Spar', color: '#2E7D32', type: 'convenience', parent: 'NorgesGruppen' },
    meny: { id: 'meny', name: 'Meny', color: '#1565C0', type: 'supermarket', parent: 'NorgesGruppen' },
    'coop-mega': { id: 'coop-mega', name: 'Coop Mega', color: '#00529B', type: 'supermarket', parent: 'Coop Norge' },
    'coop-marked': { id: 'coop-marked', name: 'Coop Marked', color: '#00529B', type: 'convenience', parent: 'Coop Norge' },
    naerbutikken: { id: 'naerbutikken', name: 'Naerbutikken', color: '#795548', type: 'convenience', parent: 'NorgesGruppen' },
    matkroken: { id: 'matkroken', name: 'Matkroken', color: '#607D8B', type: 'convenience', parent: 'NorgesGruppen' },
    obs: { id: 'obs', name: 'Obs', color: '#00529B', type: 'hypermarket', parent: 'Coop Norge' },
  },
  chainParents: {
    rema: 'Reitangruppen',
    kiwi: 'NorgesGruppen',
    extra: 'Coop Norge',
    'coop-prix': 'Coop Norge',
    bunnpris: 'Bunnpris AS',
    joker: 'NorgesGruppen',
    spar: 'NorgesGruppen',
    meny: 'NorgesGruppen',
    'coop-mega': 'Coop Norge',
    'coop-marked': 'Coop Norge',
    naerbutikken: 'NorgesGruppen',
    matkroken: 'NorgesGruppen',
    obs: 'Coop Norge',
  },
  parentColors: {
    NorgesGruppen: '#1565C0',
    'Coop Norge': '#E30613',
    Reitangruppen: '#4CAF50',
    'Bunnpris AS': '#E91E63',
  },
  dataFiles: {
    stores: 'stores.json',
    municipalities: 'municipalities.json',
    boundaries: 'norway-municipalities.geojson',
    aquaculture: 'aquaculture_sites.geojson',
    processing: 'processing-establishments.geojson',
    ports: 'ports-register.geojson',
    logistics: 'wholesale-logistics.geojson',
    farms: 'farm-foretak-by-kommune.json',
  },
  dataSources: [
    {
      layer: 'Butikker',
      file: 'stores.json',
      records: '3 849 lokasjoner',
      source: 'OpenStreetMap (Overpass API)',
      sourceUrl: 'https://overpass-turbo.eu/',
      updated: '2024-Q4',
      limitations: 'OSM-dekning varierer etter region. Noen butikker kan mangle eller være nedlagt. Kjedetilknytning basert på brand-tag.',
      reproduce: 'Overpass-spørring: shop=supermarket og shop=convenience innenfor Norge',
    },
    {
      layer: 'Kommunegrenser',
      file: 'norway-municipalities.geojson',
      records: '357 kommuner',
      source: 'Geonorge — Kartverket administrative enheter',
      sourceUrl: 'https://www.geonorge.no/',
      updated: '2024',
      limitations: 'Forenklet geometri (10%) for nettytelse. Ikke egnet for presise arealberegninger.',
    },
    {
      layer: 'Kommunedata',
      file: 'municipalities.json',
      records: '357 kommuner med demografi',
      source: 'SSB Tabell 07459 (befolkning), 06944 (inntekt), 09747 (husholdninger)',
      sourceUrl: 'https://www.ssb.no/',
      updated: '2024',
      limitations: 'Medianinntekt er 2022-data. Aldersfordeling avrundet til 1 desimal.',
    },
    {
      layer: 'Akvakultur',
      file: 'aquaculture_sites.geojson',
      records: '1 782 lokaliteter',
      source: 'Fiskeridirektoratet Akvakulturregisteret',
      sourceUrl: 'https://www.fiskeridir.no/Akvakultur/Registre-og-skjema/Akvakulturregisteret',
      updated: '2024',
      limitations: 'Alle lokaliteter er aktive (klarert). Kapasitet er tillatt, ikke faktisk produksjon, og oppgis i ulike enheter. Innehaver hentes fra databasen der lokaliteten er koblet til et selskap.',
    },
    {
      layer: 'Landbruksforetak',
      file: 'farm-foretak-by-kommune.json',
      records: '53 933 foretak i 354 kommuner',
      source: 'Landbruksdirektoratet — Foretak (åpne data)',
      sourceUrl: 'https://github.com/LandbruksdirektoratetGIT/opendata/tree/main/datasets/foretak',
      updated: '2026-09',
      limitations: 'Antall registrerte foretak per kommune, ikke aktive gårdsbruk (SSB har 36 627 for 2025). Vises i kommunens midtpunkt. Enkeltforetak vises ikke, fordi registeret identifiserer enkeltpersonforetak.',
      reproduce: 'npm run fetch:farm-foretak',
    },
    {
      layer: 'Foredlingsanlegg',
      file: 'processing-establishments.geojson',
      records: '1 343 godkjente virksomheter + 414 talt per kommune',
      source: 'Mattilsynet — godkjente virksomheter (næringsmidler, fiskerivarer); posisjon fra Kartverket Matrikkelen adresse; organisasjon fra Brønnøysundregistrene',
      sourceUrl: 'https://www.mattilsynet.no/godkjente-produkter-og-virksomheter',
      updated: '2026-09-14',
      limitations: 'Bare virksomheter godkjent av Mattilsynet (animalske næringsmidler og generell aktivitet), ikke alle matprodusenter. 311 punkter står på postnummerets midtpunkt. Enkeltpersonforetak (238) og virksomheter uten treff i Enhetsregisteret (176) vises bare som antall per kommune. Fartøy (282) og 20 anlegg uten posisjon er utelatt. Mattilsynet oppgir ingen lisens; gjengitt med kildehenvisning.',
      reproduce: 'npm run fetch:processing-establishments',
    },
    {
      layer: 'Havner',
      file: 'ports-register.geojson',
      records: '766 fiskerihavner + 634 ISPS-havneanlegg',
      source: 'Kystverket — Fiskerihavner og ISPS havneanlegg (WFS, NLOD 2.0); sted og kommune fra Kartverket Matrikkelen adresse',
      sourceUrl: 'https://kartkatalog.geonorge.no/metadata/uuid/fabfe189-06b5-4a3f-84ba-3c48b02ce6de',
      updated: '2026-09-14',
      limitations: 'Fiskerihavnene har ingen navn i registeret; de er merket med nærmeste poststed (8 har ingen adresse innen 5 km). ISPS-havneanlegg er anlegg for utenriks skipsfart, også olje- og gassanlegg. Eier vises bare når den er offentlig eller har selskapsform. Ingen tonnasje; landingsvolum kommer fra Fiskeridirektoratet senere.',
      reproduce: 'npm run fetch:ports-register',
    },
    {
      layer: 'Engros og lager',
      file: 'wholesale-logistics.geojson',
      records: '203 enheter (197 engroshandel, 6 lager)',
      source: 'Brønnøysundregistrene — Enhetsregisteret, underenheter med næringskode 46.3 og 52.1 (NLOD); posisjon fra Kartverket Matrikkelen adresse',
      sourceUrl: 'https://data.brreg.no/enhetsregisteret/oppslag/underenheter',
      updated: '2026-09-14',
      limitations: 'Aktive underenheter med minst 20 ansatte. Næringskoden sier hva virksomheten driver med, ikke om stedet er et lager: laget har også salgs- og hovedkontorer, blant annet importører av drikke og kaffe. Tobakk (46.35) er utelatt. Lagring (52.1) er bare med når hovedenheten driver med mat eller navnet viser kjøle-, fryse- eller matlager; 25 generelle tredjepartslagre er utelatt. Store dagligvarelagre med annen næringskode mangler, for eksempel Coop-lageret på Langhus (46.49). 16 punkter står på postnummerets midtpunkt, og 1 enhet uten posisjon er utelatt.',
      reproduce: 'npm run fetch:wholesale-logistics',
    },
    {
      layer: 'Matørken (analyse)',
      file: 'Beregnet',
      records: '5 km dekningsradius',
      source: 'Avledet fra butikklokasjoner med @turf/turf',
      updated: 'Beregnet i sanntid',
      limitations: 'Basert på luftlinje, ikke faktisk reiseavstand. Forutsetter lik tilgjengelighet i alle retninger.',
    },
    {
      layer: 'Sårbarhet (analyse)',
      file: 'Beregnet',
      records: 'Relativ rangering, 3 faktorer',
      source: 'Persentilrangering: avstand til nærmeste dagligvaregrossist (37,5 %), butikktetthet (37,5 %), befolkningstetthet (25 %)',
      updated: 'Beregnet i sanntid',
      limitations: 'Viser hvilke kommuner som er relativt mest utsatt, ikke absolutt risiko. Hvert nivå har omtrent like mange kommuner. Grossistavstand er luftlinje fra kommunens midtpunkt til nærmeste enhet i Enhetsregisteret med engroshandel med bredt utvalg av nærings- og nytelsesmidler (46.39) og minst 20 ansatte. Noen av disse er salgs- eller hovedkontorer, og lagre med annen næringskode mangler. Butikker per innbygger får små øykommuner til å se godt dekket ut, og faktorvektene er skjønn.',
    },
  ],
}
