import type { CountryConfig } from '../countries'

export const norwayConfig: CountryConfig = {
  code: 'no',
  name: 'Norge',
  center: [65, 13],
  zoom: 5,
  selfSufficiency: 0.45,
  municipalityIdProp: 'kommunenummer',
  municipalityNameProp: 'kommunenavn',
  chains: {
    rema: { id: 'rema', name: 'Rema 1000', color: '#E30613', type: 'discount', parent: 'Reitangruppen' },
    kiwi: { id: 'kiwi', name: 'Kiwi', color: '#4CAF50', type: 'discount', parent: 'NorgesGruppen' },
    extra: { id: 'extra', name: 'Extra', color: '#FFC107', type: 'discount', parent: 'Coop Norge' },
    'coop-prix': { id: 'coop-prix', name: 'Coop Prix', color: '#00529B', type: 'discount', parent: 'Coop Norge' },
    bunnpris: { id: 'bunnpris', name: 'Bunnpris', color: '#E91E63', type: 'discount', parent: 'Bunnpris AS' },
    joker: { id: 'joker', name: 'Joker', color: '#F44336', type: 'convenience', parent: 'NorgesGruppen' },
    spar: { id: 'spar', name: 'Spar', color: '#2E7D32', type: 'convenience', parent: 'NorgesGruppen' },
    meny: { id: 'meny', name: 'Meny', color: '#1565C0', type: 'supermarket', parent: 'NorgesGruppen' },
    'coop-mega': { id: 'coop-mega', name: 'Coop Mega', color: '#00529B', type: 'supermarket', parent: 'Coop Norge' },
    'coop-marked': { id: 'coop-marked', name: 'Coop Marked', color: '#00529B', type: 'convenience', parent: 'Coop Norge' },
    naerbutikken: { id: 'naerbutikken', name: 'Naerbutikken', color: '#795548', type: 'convenience', parent: 'NorgesGruppen' },
    matkroken: { id: 'matkroken', name: 'Matkroken', color: '#607D8B', type: 'convenience', parent: 'NorgesGruppen' },
    obs: { id: 'obs', name: 'Obs', color: '#00529B', type: 'hypermarket', parent: 'Coop Norge' },
  },
  chainParents: {
    rema: 'Reitangruppen',
    kiwi: 'NorgesGruppen',
    extra: 'Coop Norge',
    'coop-prix': 'Coop Norge',
    bunnpris: 'Bunnpris AS',
    joker: 'NorgesGruppen',
    spar: 'NorgesGruppen',
    meny: 'NorgesGruppen',
    'coop-mega': 'Coop Norge',
    'coop-marked': 'Coop Norge',
    naerbutikken: 'NorgesGruppen',
    matkroken: 'NorgesGruppen',
    obs: 'Coop Norge',
  },
  parentColors: {
    NorgesGruppen: '#1565C0',
    'Coop Norge': '#E30613',
    Reitangruppen: '#4CAF50',
    'Bunnpris AS': '#E91E63',
  },
  processingCompanies: ['Nortura', 'Tine', 'BAMA', 'Orkla', 'Lerøy', 'Mowi'],
  dataFiles: {
    stores: 'stores.json',
    municipalities: 'municipalities.json',
    boundaries: 'norway-municipalities.geojson',
    aquaculture: 'aquaculture_sites.geojson',
    processing: 'processing_plants.geojson',
    ports: 'ports.geojson',
    logistics: 'logistics_hubs.geojson',
  },
  dataSources: [
    {
      layer: 'Butikker',
      file: 'stores.json',
      records: '3 849 lokasjoner',
      source: 'OpenStreetMap (Overpass API)',
      sourceUrl: 'https://overpass-turbo.eu/',
      updated: '2024-Q4',
      limitations: 'OSM-dekning varierer etter region. Noen butikker kan mangle eller være nedlagt. Kjedetilknytning basert på brand-tag.',
      reproduce: 'Overpass-spørring: shop=supermarket og shop=convenience innenfor Norge',
    },
    {
      layer: 'Kommunegrenser',
      file: 'norway-municipalities.geojson',
      records: '357 kommuner',
      source: 'Geonorge — Kartverket administrative enheter',
      sourceUrl: 'https://www.geonorge.no/',
      updated: '2024',
      limitations: 'Forenklet geometri (10%) for nettytelse. Ikke egnet for presise arealberegninger.',
    },
    {
      layer: 'Kommunedata',
      file: 'municipalities.json',
      records: '357 kommuner med demografi',
      source: 'SSB Tabell 07459 (befolkning), 06944 (inntekt), 09747 (husholdninger)',
      sourceUrl: 'https://www.ssb.no/',
      updated: '2024',
      limitations: 'Medianinntekt er 2022-data. Aldersfordeling avrundet til 1 desimal.',
    },
    {
      layer: 'Akvakultur',
      file: 'aquaculture_sites.geojson',
      records: '1 782 anlegg',
      source: 'Fiskeridirektoratet Akvakulturregisteret',
      sourceUrl: 'https://www.fiskeridir.no/Akvakultur/Registre-og-skjema/Akvakulturregisteret',
      updated: '2024',
      limitations: 'Inkluderer både aktive og inaktive anlegg. Kapasitetsverdier er tillatt, ikke faktisk produksjon.',
    },
    {
      layer: 'Foredlingsanlegg',
      file: 'processing_plants.geojson',
      records: '30 anlegg',
      source: 'Nortura, Tine, BAMA, Orkla, Lerøy, Mowi — årsrapporter og nettsider',
      updated: '2024-Q1',
      limitations: 'Ikke uttømmende. Fokuserer på store aktører. Kapasitetstall er omtrentlige.',
    },
    {
      layer: 'Havner',
      file: 'ports.geojson',
      records: '25 havner',
      source: 'Fiskeridirektoratet, Kystverket',
      sourceUrl: 'https://www.fiskeridir.no/',
      updated: '2024',
      limitations: 'Årlig tonnasje er omtrentlig. Kun havner med betydelig matrelatert trafikk.',
    },
    {
      layer: 'Logistikkhub',
      file: 'logistics_hubs.geojson',
      records: '19 distribusjonssentre',
      source: 'ASKO (NorgesGruppen), Coop Logistikk, Rema Distribusjon — årsrapporter',
      updated: '2024',
      limitations: 'Kapasitet og butikker-betjent er omtrentlig. Mindre regionale hub-er kan mangle.',
    },
    {
      layer: 'Matørken (analyse)',
      file: 'Beregnet',
      records: '5 km dekningsradius',
      source: 'Avledet fra butikklokasjoner med @turf/turf',
      updated: 'Beregnet i sanntid',
      limitations: 'Basert på luftlinje, ikke faktisk reiseavstand. Forutsetter lik tilgjengelighet i alle retninger.',
    },
    {
      layer: 'Sårbarhet (analyse)',
      file: 'Beregnet',
      records: '4-faktor risikomodell',
      source: 'Vektet modell: hub-avstand (30%), butikktetthet (30%), selvforsyning (20%), befolkningstetthet (20%)',
      updated: 'Beregnet i sanntid',
      limitations: 'Modellen er en forenkling. Selvforsyningsgrad er nasjonal baseline (45%). Faktorvekter er ekspertvurdering.',
    },
  ],
}
