import type { CountryConfig } from '../countries'

export const swedenConfig: CountryConfig = {
  code: 'se',
  name: 'Sverige',
  center: [63, 16],
  zoom: 5,
  selfSufficiency: 0.50,
  municipalityIdProp: 'kommunkod',
  municipalityNameProp: 'kommunnamn',
  chains: {
    'ica-n-ra': { id: 'ica-n-ra', name: 'ICA Nara', color: '#E3000B', type: 'convenience', parent: 'ICA Gruppen' },
    'ica-supermarket': { id: 'ica-supermarket', name: 'ICA Supermarket', color: '#E3000B', type: 'supermarket', parent: 'ICA Gruppen' },
    'ica-kvantum': { id: 'ica-kvantum', name: 'ICA Kvantum', color: '#C40009', type: 'supermarket', parent: 'ICA Gruppen' },
    'maxi-ica-stormarknad': { id: 'maxi-ica-stormarknad', name: 'Maxi ICA Stormarknad', color: '#A50008', type: 'hypermarket', parent: 'ICA Gruppen' },
    ica: { id: 'ica', name: 'ICA', color: '#E3000B', type: 'supermarket', parent: 'ICA Gruppen' },
    'ica-maxi': { id: 'ica-maxi', name: 'ICA Maxi', color: '#A50008', type: 'hypermarket', parent: 'ICA Gruppen' },
    coop: { id: 'coop', name: 'Coop', color: '#00529B', type: 'supermarket', parent: 'Coop Sverige' },
    'coop-sweden': { id: 'coop-sweden', name: 'Coop (Sweden)', color: '#00529B', type: 'supermarket', parent: 'Coop Sverige' },
    'coop-konsum': { id: 'coop-konsum', name: 'Coop Konsum', color: '#003D74', type: 'supermarket', parent: 'Coop Sverige' },
    'coop-n-ra': { id: 'coop-n-ra', name: 'Coop Nara', color: '#00529B', type: 'convenience', parent: 'Coop Sverige' },
    'x-tra': { id: 'x-tra', name: 'X:-tra', color: '#00529B', type: 'discount', parent: 'Coop Sverige' },
    willys: { id: 'willys', name: 'Willys', color: '#00843D', type: 'discount', parent: 'Axfood' },
    'hemk-p': { id: 'hemk-p', name: 'Hemkop', color: '#006B31', type: 'supermarket', parent: 'Axfood' },
    tempo: { id: 'tempo', name: 'Tempo', color: '#00843D', type: 'convenience', parent: 'Axfood' },
    'handlar-n': { id: 'handlar-n', name: "Handlar'n", color: '#005224', type: 'convenience', parent: 'Axfood' },
    handlarn: { id: 'handlarn', name: 'Handlarn', color: '#005224', type: 'convenience', parent: 'Axfood' },
    'mat-ppet': { id: 'mat-ppet', name: 'Matoppet', color: '#00843D', type: 'convenience', parent: 'Axfood' },
    lidl: { id: 'lidl', name: 'Lidl', color: '#0050AA', type: 'discount', parent: 'Lidl' },
    'city-gross': { id: 'city-gross', name: 'City Gross', color: '#FF6900', type: 'hypermarket', parent: 'Bergendahls' },
  },
  chainParents: {
    'ica-n-ra': 'ICA Gruppen',
    'ica-supermarket': 'ICA Gruppen',
    'ica-kvantum': 'ICA Gruppen',
    'maxi-ica-stormarknad': 'ICA Gruppen',
    ica: 'ICA Gruppen',
    'ica-maxi': 'ICA Gruppen',
    coop: 'Coop Sverige',
    'coop-sweden': 'Coop Sverige',
    'coop-konsum': 'Coop Sverige',
    'coop-n-ra': 'Coop Sverige',
    'x-tra': 'Coop Sverige',
    willys: 'Axfood',
    'hemk-p': 'Axfood',
    tempo: 'Axfood',
    'handlar-n': 'Axfood',
    handlarn: 'Axfood',
    'mat-ppet': 'Axfood',
    lidl: 'Lidl',
    'city-gross': 'Bergendahls',
  },
  parentColors: {
    'ICA Gruppen': '#E3000B',
    Axfood: '#00843D',
    'Coop Sverige': '#00529B',
    Lidl: '#0050AA',
    Bergendahls: '#FF6900',
  },
  processingCompanies: [],
  dataFiles: {
    stores: 'stores.json',
    municipalities: 'municipalities.json',
    boundaries: 'municipalities.geojson',
  },
  dataSources: [
    {
      layer: 'Butiker',
      file: 'stores.json',
      records: '5 049 platser',
      source: 'OpenStreetMap (Overpass API)',
      sourceUrl: 'https://overpass-turbo.eu/',
      updated: '2024-Q4',
      limitations: 'OSM-tackning varierar efter region. Vissa butiker kan saknas eller vara nedlagda. Kedjetillhorighet baserad pa brand-tagg.',
      reproduce: 'Overpass-fraga: shop=supermarket och shop=convenience inom Sverige',
    },
  ],
}
