export type GlossaryCategory = 'statistikk' | 'prosjekt' | 'status' | 'kolonner'

export type GlossaryTerm = {
  term: string
  definition: string
  reading?: string
  category: GlossaryCategory
}

export const GLOSSARY_TERMS: GlossaryTerm[] = [
  // statistikk — moved verbatim from InsightGlossary
  { term: 'HHI', category: 'statistikk', definition: 'Herfindahl-Hirschman Index — sum av kvadrerte markedsandeler. Viser konsentrasjon i markedet.', reading: '< 1500 lavt · 1500–2500 moderat · > 2500 høyt konsentrert' },
  { term: 'Gini', category: 'statistikk', definition: 'Gini-koeffisient — mål på ulikhet i fordeling. Her brukt på butikktilgang per innbygger.', reading: '0 = perfekt likhet · 1 = maksimal ulikhet' },
  { term: 'CR3', category: 'statistikk', definition: 'Concentration Ratio 3 — samlet markedsandel for de tre største aktørene.', reading: '> 70% indikerer oligopol' },
  { term: 'Zipf', category: 'statistikk', definition: 'Zipfs lov — empirisk fordeling der antall ≈ konstant / rang. Brukes til å sjekke om butikknettverket følger naturlig urban-fordeling.', reading: 'R² nær 1 og helling ≈ −1 = følger Zipf' },
  { term: 'Lorenz-kurve', category: 'statistikk', definition: 'Visuell fremstilling av ulikhet. Diagonalen = perfekt likhet; jo lengre kurven bøyer ut, jo større ulikhet.' },
  // prosjekt — 6 from the forside Nøkkelbegreper + 3 new
  { term: 'Food TG', category: 'prosjekt', definition: 'Food Transition Group, prosjektets arbeidsgruppe.' },
  { term: 'Ten Step', category: 'prosjekt', definition: 'Ti-stegs metodikk for å drive transisjonsgruppen.' },
  { term: 'Evidence Pack', category: 'prosjekt', definition: 'Standardsettet av leveransedokumenter.' },
  { term: 'Spor A/B/C', category: 'prosjekt', definition: 'De tre scope-sporene: fôr/import, sidestrømmer, governance.' },
  { term: 'Claim-koder', category: 'prosjekt', definition: 'CL = claim, EV = evidence, SRC = kilde, med spor og nummer.' },
  { term: 'Forskningsrunder', category: 'prosjekt', definition: 'Avgrensede runder med kunnskapsinnhenting.' },
  { term: 'SourceDoc', category: 'prosjekt', definition: 'Kilde-lag i databasen med proveniens; et bibliotek-dokument kan finnes uten et eget SourceDoc-lag.' },
  { term: 'Backlog', category: 'prosjekt', definition: 'Kilder identifisert i en forskningsrunde, men ikke ennå registrert eller nedlastet.' },
  { term: 'Exa', category: 'prosjekt', definition: 'Søke-API brukt til å hente kilder automatisk.' },
  // status — badge codes
  { term: 'Stance', category: 'status', definition: 'Aktørens holdning til prosjektet (teamets vurdering, ikke aktørens egen uttalelse).', reading: 'champion = forkjemper · supportive = støttende · neutral = nøytral · skeptical = skeptisk · opposed = motstander' },
  { term: 'Prioritet (P1–P3)', category: 'status', definition: 'Intern prioritering av aktør for oppfølging.', reading: 'P1 = viktigst · P3 = lavest' },
  { term: 'Researchstatus', category: 'status', definition: 'Hvor sikkert et tall er.', reading: 'Primærsnapshot = bekreftet fra primærkilde på ett tidspunkt · Proxy/modell = indirekte indikator · Trenger primærsjekk = må verifiseres mot primærkilde' },
  { term: 'Innsiktstype', category: 'status', definition: 'Kilde-/dokumenttype bak en innsikt.', reading: 'Notat · Transkripsjon · Arbeidsdok · Strategi · Duplikat = overlapper en annen oppføring' },
  { term: 'Claim-status', category: 'status', definition: 'Arbeidsstatus for en påstand i claim-registeret: om den er foreslått, kildebelagt, klar for bruk eller trenger ny verifisering.' },

  // kolonner — shared explanations used by list and table surfaces
  { term: 'Navn', category: 'kolonner', definition: 'Visningsnavn på personen, produsenten, lokaliteten eller oppføringen slik den brukes i registeret.' },
  { term: 'Selskapsnavn', category: 'kolonner', definition: 'Juridisk eller kuratert selskapsnavn koblet til registerrad, regnskap, eierskap eller relasjoner.' },
  { term: 'Organisasjonsnummer', category: 'kolonner', definition: 'Ni-sifret norsk organisasjonsnummer brukt som stabil nøkkel mot offentlige registre og importerte datasett.' },
  { term: 'Kommune', category: 'kolonner', definition: 'Kommunen radens hovedadresse, produsent, eiendom eller havbrukslokalitet er knyttet til.' },
  { term: 'Fylke', category: 'kolonner', definition: 'Fylke brukt som regional gruppering når kildedataene gir kommune- eller lokalitetsplassering.' },
  { term: 'Land', category: 'kolonner', definition: 'Landkode eller landnavn for selskapets registrerte tilhørighet eller innsiktens geografiske relevans.' },
  { term: 'NACE', category: 'kolonner', definition: 'Standard næringskode fra foretaksregisteret. Brukes som bransjeklassifisering, ikke som prosjektets egen verdikjedevurdering.' },
  { term: 'Verdikjedetrinn', category: 'kolonner', definition: 'Prosjektets kuraterte plassering av selskapet i matsystemets verdikjede, for eksempel produksjon, foredling, dagligvare eller logistikk.' },
  { term: 'Eierskapstype', category: 'kolonner', definition: 'Prosjektets grove eierskapsklassifisering, for eksempel familie, samvirke, stat, utenlandsk, børsnotert eller privat.' },
  { term: 'Juridisk form', category: 'kolonner', definition: 'Foretaksform fra registerdata, for eksempel AS, SA eller ENK. Dette er ikke det samme som eierskapstype.' },
  { term: 'Stiftelsesår', category: 'kolonner', definition: 'Året selskapet eller foretaket er registrert stiftet når feltet finnes i kildedataene.' },
  { term: 'Omsetning', category: 'kolonner', definition: 'Driftsinntekter eller annen omsetningsvisning fra siste tilgjengelige regnskapsrad, formatert for oversiktsbruk.' },
  { term: 'Ansatte', category: 'kolonner', definition: 'Registrert antall ansatte fra importerte register- eller regnskapsdata når feltet er tilgjengelig.' },
  { term: 'Kontrollerende eier', category: 'kolonner', definition: 'Eier eller konsern som prosjektet har koblet som kontrollerende aktør for selskapet.' },
  { term: 'Dekningsstatus', category: 'kolonner', definition: 'Intern indikator for om et selskap har koblede data som regnskap, styre, eierskap eller andre relasjoner.' },
  { term: 'Aktørtype', category: 'kolonner', definition: 'Prosjektets klassifisering av en interessent, for eksempel selskap, offentlig organ, bransjeaktør eller forskningsmiljø.' },
  { term: 'Organisasjonstype', category: 'kolonner', definition: 'Mer detaljert organisasjonsform eller rolle for aktøren når dette er registrert.' },
  { term: 'Stance', category: 'kolonner', definition: 'Aktørens holdning til prosjektet slik teamet vurderer den internt.', reading: 'champion = forkjemper · supportive = støttende · neutral = nøytral · skeptical = skeptisk · opposed = motstander' },
  { term: 'Prioritet (P1–P3)', category: 'kolonner', definition: 'Intern prioritering av aktør for oppfølging.', reading: 'P1 = viktigst · P3 = lavest' },
  { term: 'Makt', category: 'kolonner', definition: 'Intern 1–5-vurdering av hvor stor påvirkningskraft aktøren har i prosjektets kontekst.' },
  { term: 'Interesse', category: 'kolonner', definition: 'Intern 1–5-vurdering av hvor relevant eller engasjert aktøren antas å være for prosjektets arbeid.' },
  { term: 'Specific ask', category: 'kolonner', definition: 'Konkret forespørsel eller ønsket handling teamet vurderer for aktøren.' },
  { term: 'Neste steg', category: 'kolonner', definition: 'Planlagt oppfølging eller neste arbeidsoppgave knyttet til aktøren.' },
  { term: 'Ansvar', category: 'kolonner', definition: 'Intern eier eller ansvarlig person for oppfølging av raden.' },
  { term: 'Tema', category: 'kolonner', definition: 'Tematag brukt for filtrering og gruppering av aktører, innsikter eller kilder.' },
  { term: 'Koblet selskap', category: 'kolonner', definition: 'Selskapspost i registeret som er koblet til aktøren eller oppføringen.' },
  { term: 'Lokalitet', category: 'kolonner', definition: 'Havbrukslokalitet med navn eller lokalitetsnummer fra Fiskeridirektoratets åpne data.' },
  { term: 'Operatør', category: 'kolonner', definition: 'Selskapet som er koblet til havbrukslokaliteten eller operatørraden.' },
  { term: 'Kapasitet', category: 'kolonner', definition: 'Registrert kapasitet for lokaliteten, normalt maksimal tillatt biomasse når enheten er tonn.' },
  { term: 'MTB', category: 'kolonner', definition: 'Maksimal tillatt biomasse. Brukes som kapasitetsmål i havbruksdata.' },
  { term: 'Lokalitetsandel', category: 'kolonner', definition: 'Operatørens andel av alle viste havbrukslokaliteter i oversikten.' },
  { term: 'Art', category: 'kolonner', definition: 'Fiske- eller skalldyrart som er registrert for lokaliteten eller søknaden.' },
  { term: 'Konsesjonsstatus', category: 'kolonner', definition: 'Statusfelt for havbrukslokalitet eller tillatelse, for eksempel aktiv, pauset eller avviklet.' },
  { term: 'Søknad', category: 'kolonner', definition: 'Havbrukssøknad med tittel eller søknadsnummer fra kildedataene.' },
  { term: 'Søker', category: 'kolonner', definition: 'Selskap eller organisasjonsnummer som står som søker på havbrukssøknaden.' },
  { term: 'Søknadstype', category: 'kolonner', definition: 'Kildens klassifisering av hva slags havbrukssøknad raden gjelder.' },
  { term: 'Opprettet', category: 'kolonner', definition: 'Datoen søknaden ble registrert opprettet i kildedataene.' },
  { term: 'Søknadsresultat', category: 'kolonner', definition: 'Resultatstatus for søknaden, for eksempel innvilget, avslått, innenfor regelverk eller fortsatt pågående.' },
  { term: 'Eiendomstype', category: 'kolonner', definition: 'Prosjektets klassifisering av eiendommen, for eksempel butikk, lager, kontor, produksjon eller logistikk.' },
  { term: 'Eiendomsselskapstype', category: 'kolonner', definition: 'Prosjektets klassifisering av eiendomsselskapets rolle, for eksempel eierselskap, driftsselskap eller regionalt eiendomsselskap.' },
  { term: 'Adresse', category: 'kolonner', definition: 'Gateadresse eller stedfesting slik den er registrert i eiendomsdatasettet.' },
  { term: 'Areal', category: 'kolonner', definition: 'Registrert bygnings- eller eiendomsareal i kvadratmeter når feltet finnes.' },
  { term: 'Leietaker', category: 'kolonner', definition: 'Selskapet som er koblet som leietaker i eiendomsdatasettet.' },
  { term: 'Leiestatus', category: 'kolonner', definition: 'Om eiendommen er markert som selvleie innen konsernet eller ekstern leie.' },
  { term: 'Sum eiendeler', category: 'kolonner', definition: 'Bokført total eiendelssum i regnskapsåret for eiendomsselskapet.' },
  { term: 'EK-andel', category: 'kolonner', definition: 'Egenkapitalandel beregnet som egenkapital delt på sum eiendeler.' },
  { term: 'Driftsinntekter', category: 'kolonner', definition: 'Regnskapsført driftsinntekt for selskapet i valgt år.' },
  { term: 'Driftsresultat', category: 'kolonner', definition: 'Regnskapsført resultat fra drift før finansposter og skatt.' },
  { term: 'År', category: 'kolonner', definition: 'Regnskapsår, kildeår eller publiseringsår avhengig av hvilken liste raden står i.' },
  { term: 'Kilde', category: 'kolonner', definition: 'Kildepost, dokument eller backlog-rad som ligger til grunn for analysen.' },
  { term: 'Kildetittel', category: 'kolonner', definition: 'Tittel eller filnavn som identifiserer kilden i kilderegisteret.' },
  { term: 'Kildetype', category: 'kolonner', definition: 'Kildens dokument- eller materialtype, for eksempel NOU, rapport, statistikk, søknad eller arbeidsdokument.' },
  { term: 'Utgiver', category: 'kolonner', definition: 'Forfatter, institusjon eller annen avsender som står bak kilden.' },
  { term: 'Beskrivelse', category: 'kolonner', definition: 'Kort intern forklaring av hva kilden eller raden dekker.' },
  { term: 'Lenke', category: 'kolonner', definition: 'Tilgjengelig handling for å åpne originalkilde, bibliotekpost eller ekstern URL.' },
  { term: 'Nedlastingsstatus', category: 'kolonner', definition: 'Intern status for om kilden er lastet ned, hentet med Exa, krever manuell nedlasting, bare har URL, mangler metadata eller ikke er sporet i backlog.' },
  { term: 'Forskningsrunde', category: 'kolonner', definition: 'Arbeidsrunde eller backlog-batch der kilden eller funnet ble identifisert.' },
  { term: 'Kildeopprinnelse', category: 'kolonner', definition: 'Hvor raden kommer fra: database, dokumentbibliotek eller research-backlog.' },
  { term: 'Produsentnavn', category: 'kolonner', definition: 'Navn på produsenten slik den står i rå landbruksregisterdata.' },
  { term: 'Tilskudd', category: 'kolonner', definition: 'Antall tilskuddsoppføringer som er koblet til produsenten i råregisteret.' },
  { term: 'Leveranser', category: 'kolonner', definition: 'Antall leveranseoppføringer som er koblet til produsenten i råregisteret.' },
  { term: 'Innsiktstype', category: 'kolonner', definition: 'Klassifisering av innsikt eller funn, for eksempel notat, kartlegging, analyse, funn eller lenke.' },
  { term: 'Dato', category: 'kolonner', definition: 'Dato knyttet til innsikten eller dokumentgrunnlaget når dette finnes.' },
  { term: 'Fase', category: 'kolonner', definition: 'Prosjektfase eller arbeidsfase innsikten er koblet til.' },
  { term: 'Tagger', category: 'kolonner', definition: 'Emneord brukt for å filtrere eller gruppere innsikter på tvers av land og tema.' },
  { term: 'Claim-status', category: 'kolonner', definition: 'Arbeidsstatus for en påstand i claim-registeret, brukt for å skille forslag, kildebelagte claims og claims som må verifiseres på nytt.' },
]

export function getGlossaryTerm(term: string, category?: GlossaryCategory) {
  return GLOSSARY_TERMS.find((entry) => {
    if (entry.term !== term) return false
    return category ? entry.category === category : true
  })
}

export const LIST_SURFACE_GLOSSARY_TERMS = {
  selskap: [
    'Selskapsnavn',
    'Organisasjonsnummer',
    'Kommune',
    'NACE',
    'Verdikjedetrinn',
    'Eierskapstype',
    'Juridisk form',
    'Stiftelsesår',
    'Land',
    'Omsetning',
    'Ansatte',
    'Kontrollerende eier',
    'Dekningsstatus',
  ],
  aktorer: [
    'Aktørtype',
    'Organisasjonstype',
    'Stance',
    'Prioritet (P1–P3)',
    'Makt',
    'Interesse',
    'Specific ask',
    'Neste steg',
    'Ansvar',
    'Tema',
    'Koblet selskap',
  ],
  havbruk: [
    'Lokalitet',
    'Operatør',
    'Kommune',
    'Kapasitet',
    'MTB',
    'Lokalitetsandel',
    'Art',
    'Konsesjonsstatus',
    'Søknad',
    'Søker',
    'Søknadstype',
    'Opprettet',
    'Søknadsresultat',
  ],
  eiendommer: [
    'Selskapsnavn',
    'Eiendomstype',
    'Eiendomsselskapstype',
    'Adresse',
    'Kommune',
    'Areal',
    'Leietaker',
    'Leiestatus',
    'Sum eiendeler',
    'EK-andel',
    'Driftsinntekter',
    'Driftsresultat',
    'År',
  ],
  kilder: [
    'Kilde',
    'Kildetittel',
    'Kildetype',
    'Utgiver',
    'År',
    'Beskrivelse',
    'Lenke',
    'Nedlastingsstatus',
    'Forskningsrunde',
    'Kildeopprinnelse',
  ],
  produsenter: [
    'Produsentnavn',
    'Organisasjonsnummer',
    'Kommune',
    'Tilskudd',
    'Leveranser',
  ],
  innsikt: [
    'Innsiktstype',
    'Kilde',
    'Dato',
    'Fase',
    'Tagger',
    'Forskningsrunde',
    'Kildeopprinnelse',
    'Claim-status',
  ],
} as const
