/** Reproduce storage annotations from known importer contracts, without running an importer or changing amounts. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import ts from 'typescript'
import { NORDIC_MARGIN_UNIT_TARGETS } from './repair-nordic-margin-financial-units'

const target = 'prisma/migrations/20260908183000_explicit_financial_storage'
const sf = ts.createSourceFile('seed.ts', readFileSync('scripts/import-company-data.ts', 'utf8'), ts.ScriptTarget.Latest, true)
const sql = (value: string | number | null) => value == null ? 'NULL' : typeof value === 'number' ? String(value) : `'${value.replaceAll("'", "''")}'`
function literal(node: ts.Expression | undefined): string | number | null {
  if (!node) return null
  if (ts.isStringLiteral(node)) return node.text
  if (ts.isNumericLiteral(node)) return Number(node.text)
  if (ts.isPrefixUnaryExpression(node) && node.operator === ts.SyntaxKind.MinusToken && ts.isNumericLiteral(node.operand)) return -Number(node.operand.text)
  throw new Error(`Unsupported literal: ${node.getText(sf)}`)
}
function props(node: ts.ObjectLiteralExpression) {
  return new Map(node.properties.filter(ts.isPropertyAssignment).map(p => [p.name.getText(sf), p.initializer]))
}
const rows: Array<{ orgNr: string; year: number; revenueNok: number | null; operatingResult: number | null; ebitda: number | null; source: string; priorScale: number; currency: string | null; fx: number | null }> = []
function visit(node: ts.Node) {
  if (ts.isObjectLiteralExpression(node)) {
    const p = props(node), financials = p.get('financials')
    if (p.has('orgNr') && financials && ts.isArrayLiteralExpression(financials)) {
      for (const element of financials.elements) {
        if (!ts.isObjectLiteralExpression(element)) throw new Error('Expected literal financial row')
        const f = props(element)
        rows.push({ orgNr: literal(p.get('orgNr')) as string, year: literal(f.get('year')) as number,
          revenueNok: literal(f.get('revenueNok')) as number | null,
          operatingResult: literal(f.get('operatingResult')) as number | null, ebitda: null,
          source: literal(f.get('source')) as string, priorScale: 1, currency: null, fx: null })
      }
    }
  }
  ts.forEachChild(node, visit)
}
visit(sf)
for (const t of NORDIC_MARGIN_UNIT_TARGETS) {
  rows.push({ orgNr: t.orgNr, year: t.year, revenueNok: t.finalData.revenueNok,
    operatingResult: t.finalData.operatingResult, ebitda: t.finalData.ebitda,
    source: t.finalData.source, priorScale: t.finalData.unitScale,
    currency: t.finalData.reportingCurrency, fx: t.finalData.fxRateNokPerUnit })
}
// These importers explicitly multiply revenue AND operating result by 1,000,000 before writing.
// Full importer-specific labels identify a storage contract, not a source verification status.
const wholeNokSources = [
  'Brønnøysund / offentligdata MCP 2026-03', 'Broennoysund / offentligdata MCP 2026-03',
  'Leroey Annual Report 2024 / web research 2026-03', 'Mowi Annual Report 2024 / web research 2026-03',
  'SalMar Annual Report 2024 / web research 2026-03', 'BAMA Gruppen Aarsrapport 2024 / web research 2026-03',
  'Kavli Holding / Q-Meieriene aarsrapport 2024 / web research 2026-03',
]
const result = `-- Generated by scripts/build-financial-storage-migration.ts; no source amounts or authority changed.
-- Legacy seed contracts match identity, year, source, every money field and prior storage metadata.
-- Unmatched/mixed rows stay unknown. No source-word or amount-magnitude inference.
ALTER TABLE "CompanyFinancial" ADD COLUMN "amountCurrency" TEXT;
WITH contracts (org, year, revenue, result, ebitda, source, scale, currency, fx) AS (VALUES
${rows.map(r => `  (${[r.orgNr, r.year, r.revenueNok, r.operatingResult, r.ebitda, r.source, r.priorScale, r.currency, r.fx].map(sql).join(', ')})`).join(',\n')}
)
UPDATE "CompanyFinancial" f SET "amountCurrency" = 'NOK', "unitScale" = 1000000
FROM contracts v, "Company" c
WHERE c.id = f."companyId" AND c."orgNr" = v.org AND f.year = v.year
  AND f.source = v.source AND f."revenueNok" IS NOT DISTINCT FROM v.revenue
  AND f."operatingResult" IS NOT DISTINCT FROM v.result AND f.ebitda IS NOT DISTINCT FROM v.ebitda
  AND f."unitScale" = v.scale AND f."reportingCurrency" IS NOT DISTINCT FROM v.currency
  AND f."fxRateNokPerUnit" IS NOT DISTINCT FROM v.fx;

-- Known tree importers store whole NOK. Do not annotate unexpected FX or EBITDA enrichment.
UPDATE "CompanyFinancial" SET "amountCurrency" = 'NOK'
WHERE "amountCurrency" IS NULL AND "unitScale" = 1 AND "reportingCurrency" IS NULL
  AND "fxRateNokPerUnit" IS NULL AND ebitda IS NULL
  AND source IN (${wholeNokSources.map(sql).join(', ')});
`
if (process.argv.includes('--check')) {
  if (readFileSync(`${target}/migration.sql`, 'utf8') !== result) throw new Error('Financial storage migration drift')
} else {
  mkdirSync(target, { recursive: true }); writeFileSync(`${target}/migration.sql`, result)
}
console.log(JSON.stringify({ contracts: rows.length, wholeNokImporterContracts: wholeNokSources.length, mode: process.argv.includes('--check') ? 'check' : 'write' }))
