import type { SourceDoc } from "@/lib/types"

export const sources: SourceDoc[] = [
  {
    id: 'src-1',
    filename: 'Just now (12.Revise-Gab) Nordic Circular Food systems - V.2.md',
    type: 'soknad',
    description: 'Den store NI-soknaden (avslatt). Full prosjektbeskrivelse, partnere, budsjett, handlingsplan',
    relevance: 'Primaer bakgrunn - gjenbruk tekst og analyse',
  },
  {
    id: 'src-2',
    filename: '1. Food system_ Oslo Innovasjons program 2025.md',
    type: 'soknad',
    description: 'Oslo Innovasjonsprogram-soknad med bakgrunn fra Cecilie, ideer, mal',
    relevance: 'Lokal kontekst - Gamlebyen, urban food systems',
  },
  {
    id: 'src-3',
    filename: '9, mars 2026 FOOD.md',
    type: 'notat',
    description: 'Mote 9. mars med aksjonspunkter fra Einar/Martin',
    relevance: 'Oppdragsbeskrivelse - hva som skal gjores na',
  },
  {
    id: 'src-4',
    filename: 'Speaker 1.md',
    type: 'transkripsjon',
    description: 'Lengre samtale om strategi, data, verdikjeder, transition groups og nordisk merverdi',
    relevance: 'Strategisk innsikt - cascading, HORECA, data og power law',
  },
  {
    id: 'src-5',
    filename: 'Speaker 1 (1).md',
    type: 'transkripsjon',
    description: 'Samtale om a finne dokumenter, bakgrunnsmateriale og starte arbeidet',
    relevance: 'Kontekst - forsta hva som mangler og hvordan arbeidet skal rigges',
  },
  {
    id: 'src-6',
    filename: 'Untitled document.md',
    type: 'duplikat',
    description: 'Samme som 9. mars-notater med ekstra kontekst',
    relevance: 'Redundant',
    isDuplicate: true,
  },
  {
    id: 'src-7',
    filename: '2026 1401 DROFTING TRANSITION GROUPS.pdf',
    type: 'strategi',
    description: 'Cathrines 20-siders drofting: TG-metodikk, governance, branding, tjenester',
    relevance: 'Metodisk rammeverk for hele arbeidet',
  },
  {
    id: 'src-8',
    filename: '2026 TRANSITION GROUP OVERVIEW WORKING DOC.pdf',
    type: 'arbeidsdok',
    description: 'Revidert 10-step start, vurderingskriterier, felles prosesser',
    relevance: 'Operasjonell mal',
  },
  {
    id: 'src-9',
    filename: 'Natural State Mail - NCH application 2025.pdf',
    type: 'epost',
    description: 'Martin videresender NCH 2025-soknaden (Michel Bajuk justert)',
    relevance: 'Referanse - soknaden som ble innvilget',
  },
  {
    id: 'src-10',
    filename: 'Natural State Mail - DROFTING TG.pdf',
    type: 'epost',
    description: 'Cathrine deler droftingsdokumentet med Gabriel',
    relevance: 'Kontekst',
  },
  {
    id: 'src-11',
    filename: '1. Food system_ Oslo Innovasjons program 2025 (1).md',
    type: 'duplikat',
    description: 'Kopi av Oslo-soknaden',
    relevance: 'Redundant',
    isDuplicate: true,
  },
  {
    id: 'src-12',
    filename: 'nou-2011-4-sammendrag.md',
    title: 'Mat, makt og avmakt – om styrkeforholdene i verdikjeden for mat',
    author: 'Matkjedeutvalget',
    year: 2011,
    type: 'nou',
    description: 'Dokumenterte massiv maktforskyvning fra produsent til kjedenes paraplyorganisasjoner.',
    relevance: 'Grunnlagsdokument for markedskonsentrasjon og vertikal integrasjon.',
    url: 'https://www.regjeringen.no/no/dokumenter/nou-2011-4/id640128/'
  },
  {
    id: 'src-13',
    filename: 'nou-2022-14-sammendrag.md',
    title: 'Inntektsmåling i jordbruket',
    author: 'Grytten-utvalget',
    year: 2022,
    type: 'nou',
    description: 'Foreslår nye hovedmål for inntektsmåling og analyserer primærprodusentens kår.',
    relevance: 'Analyse av primærprodusentens økonomiske kår.',
    url: 'https://www.regjeringen.no/no/dokumenter/nou-2022-14/id2930144/'
  },
  {
    id: 'src-14',
    filename: 'dagligvarerapport-2024.md',
    title: 'Konkurransetilsynets Dagligvarerapport 2024-25',
    author: 'Konkurransetilsynet',
    year: 2025,
    type: 'rapport',
    description: 'Nyeste status på markedsandeler, marginer og etableringshindringer.',
    relevance: 'Oppdaterte markedstall og analyse av griskflasjon.',
    url: 'https://konkurransetilsynet.no/wp-content/uploads/2025/04/Konkurransetilsynets-Dagligvarerapport-2024-25.pdf'
  },
  {
    id: 'src-15',
    filename: 'samarbeidsklima-2025.md',
    title: 'Samarbeidsklimaet i dagligvarebransjen 2025',
    author: 'Dagligvaretilsynet',
    year: 2025,
    type: 'rapport',
    description: 'Dokumenterer det operative forholdet mellom kjeder og leverandører.',
    relevance: 'Viser utfordringer i forhandlinger og frykt for sanksjoner.',
    url: 'https://www.dagligvaretilsynet.no/'
  },
  {
    id: 'src-16',
    filename: 'beredskap-2023.md',
    title: 'Riksrevisjonens undersøkelse av matsikkerhet og beredskap på jordbruksområdet',
    author: 'Riksrevisjonen',
    year: 2023,
    type: 'rapport',
    description: 'Kritisk analyse av systemets sårbarhet og manglende kriseplanlegging.',
    relevance: 'Vurdering av nasjonal beredskap og importavhengighet.',
    url: 'https://www.riksrevisjonen.no/rapporter-mappe/no-2023-2024/matsikkerhet-og-beredskap-pa-jordbruksomradet/'
  },
  {
    id: 'src-17',
    filename: 'norgesgruppen-2024-25.md',
    title: 'Års- og bærekraftsrapport 2024 / Halvårsrapport 2025',
    author: 'NorgesGruppen ASA',
    year: 2025,
    type: 'årsrapport',
    description: 'Finansielle resultater og strategisk retning for markedslederen.',
    relevance: 'Markedsdominans og EMV-strategi.',
    url: 'https://www.norgesgruppen.no/om-oss/rapporter/'
  },
  {
    id: 'src-18',
    filename: 'coop-2024.md',
    title: 'Coops årsresultat og medlemsnytte 2024',
    author: 'Coop Norge SA',
    year: 2025,
    type: 'årsrapport',
    description: 'Samvirkemodellens resultater og vekst for Extra.',
    relevance: 'Analyse av Coop som utfordrer og medlemsnytte.',
    url: 'https://coop.no/om-coop/virksomheten/finansiell-informasjon/'
  },
  {
    id: 'src-19',
    filename: 'jacobsen-jansson-2022.md',
    title: 'Norway – the Black Sheep in the Scandinavian Grocery Industry',
    author: 'Adrian Magnus Jacobsen & Douglas Jansson',
    year: 2022,
    type: 'masteroppgave',
    description: 'Analyserer produktivitet og marginer i skandinavisk kontekst.',
    relevance: 'Utfordrer myter om ineffektivitet i norsk dagligvare.',
    url: 'https://openaccess.nhh.no/'
  },
  {
    id: 'src-20',
    filename: 'foros-media-2025.md',
    title: 'Media attention and price competition: Evidence from Norwegian grocery retailing',
    author: 'Foros, Friberg, Kind, Shaffer & Steen',
    year: 2025,
    type: 'rapport',
    description: 'Forklarer prissettingens dynamikk og medias rolle som regulator.',
    relevance: 'Innsikt i pristester og medias påvirkning på priser.',
    url: 'https://www.nhh.no/en/research-centres/food/'
  },
  {
    id: 'src-21',
    filename: 'sifo-kundeprogram-2026.md',
    title: 'Kunnskapsgrunnlag om kundeprogrammene i dagligvaremarkedet',
    author: 'SIFO (OsloMet)',
    year: 2026,
    type: 'rapport',
    description: 'Analyse av digital makt og personlig prising i kundeprogrammer.',
    relevance: 'Forståelse av lojalitetsmekanismer og digitalt skille.',
    url: 'https://oda.oslomet.no/'
  },
  {
    id: 'src-22',
    filename: 'nguyen-hartmann-2024.md',
    title: 'Restrictive covenants in the Norwegian grocery market',
    author: 'Hien Nguyen Thi Thu & Kenneth Hartmann',
    year: 2024,
    type: 'masteroppgave',
    description: 'Dokumenterer etableringshindringer gjennom strategisk bruk av eiendom.',
    relevance: 'Empirisk studie av restriktive servitutter.',
    url: 'https://openaccess.nhh.no/'
  },
  {
    id: 'src-23',
    filename: 'stockholm-resilience-2019.md',
    title: 'Nordic Food Systems for Improved Health and Sustainability',
    author: 'Stockholm Resilience Centre',
    year: 2019,
    type: 'rapport',
    description: 'Systemisk blikk på sårbarhet og transformasjonsbehov i Norden.',
    relevance: 'Bærekraft og helseperspektiv på matsystemet.',
    url: 'https://www.stockholmresilience.org/'
  },
  {
    id: 'src-24',
    filename: 'kkv-4a-dominans.md',
    title: 'Kilpailulaki (Competition Act) Section 4a',
    author: 'KKV (Finland)',
    year: 2014,
    type: 'lovverk',
    description: 'Regulering av markedsmakt med automatisk dominans-presumsjon over 30%.',
    relevance: 'Finsk benchmark for tøyling av markedsmakt.',
    url: 'https://www.kkv.fi/en/'
  },
  {
    id: 'src-25',
    filename: 'konkurrensverket-2024-5.md',
    title: 'Konkurrensverkets genomlysning av livsmedelsbranschen 2023–2024',
    author: 'Konkurrensverket (Sverige)',
    year: 2024,
    type: 'rapport',
    description: 'Analyse av inflasjon og markedsmakt i det svenske matmarkedet.',
    relevance: 'Komparativ analyse av nordiske matvarepriser.',
    url: 'https://www.konkurrensverket.se/publikationer/'
  },
  {
    id: 'src-26',
    filename: 'meld-st-11-selvforsyning.md',
    title: 'Strategi for auka sjølvforsyning av jordbruksvarer',
    author: 'Landbruks- og matdepartementet',
    year: 2024,
    type: 'rapport',
    description: 'Definerer nasjonalt mål om 50% selvforsyning innen 2030.',
    relevance: 'Sentralt styringsdokument for matsikkerhet.',
    url: 'https://www.regjeringen.no/no/dokumenter/meld-st-11-20232024/id3033241/'
  },
  {
    id: 'src-27',
    filename: 'meld-st-4-dagligvare.md',
    title: 'Anmodnings- og utredningsvedtak (Dagligvareseksjonen)',
    author: 'Nærings- og fiskeridepartementet',
    year: 2024,
    type: 'rapport',
    description: 'Status for regjeringens 10-punktsplan for dagligvarebransjen.',
    relevance: 'Politisk oppfølging av markedstiltak.',
    url: 'regjeringen.no'
  },
  {
    id: 'src-28',
    filename: 'soa-emv-2023.md',
    title: 'Kartlegging av egne merkevarer og vertikal integrasjon',
    author: 'Samfunnsøkonomisk Analyse (SØA)',
    year: 2023,
    type: 'rapport',
    description: 'Dybdeanalyse av maktforskyvning gjennom eierskap i produksjonsleddet.',
    relevance: 'Analyse av EMV-andel og vertikal integrasjon.',
    url: 'regjeringen.no'
  },
  {
    id: 'src-29',
    filename: 'dagligvarerapporten-2025.md',
    title: 'Dagligvarerapporten 2025 (Basert på 2024-tall)',
    author: 'NielsenIQ / Virke',
    year: 2025,
    type: 'rapport',
    description: 'Offisielle markedstall for norsk dagligvarebransje.',
    relevance: 'Oppdaterte markedsandeler og lavprisutvikling.',
    url: 'virke.no'
  },
  {
    id: 'src-30',
    filename: 'asko-infrastruktur-2025.md',
    title: 'ASKO Års- og bærekraftsrapport / NorgesGruppen Logistikk',
    author: 'ASKO Norge AS',
    year: 2025,
    type: 'årsrapport',
    description: 'Dokumenterer infrastruktur og logistikkens rolle i verdikjeden.',
    relevance: 'ASKOs rolle som systemkritisk aktør.',
    url: 'asko.no'
  },
  {
    id: 'src-31',
    filename: 'nibio-selvforsyning-metode.md',
    title: 'Beregning av sjølvforsyningsgrad',
    author: 'NIBIO',
    year: 2023,
    type: 'rapport',
    description: 'Metodisk grunnlag for å vurdere matsikkerhet i energi og volum.',
    relevance: 'Teknisk grunnlag for selvforsyningsdebatt.',
    url: 'nibio.no'
  },
  {
    id: 'src-32',
    filename: 'matsvinn-2024.md',
    title: 'Matsvinn i Norge 2024 — Status og utvikling',
    author: 'Matvett / NORSUS',
    year: 2025,
    type: 'rapport',
    description: 'Kvantifiserer ressurstap i hele verdikjeden.',
    relevance: 'Effektivitet i sirkulær økonomi.',
    url: 'matvett.no'
  },
  {
    id: 'src-33',
    filename: 'price-levels-2024.md',
    title: 'Purchasing Power Parities (PPP) survey results 2024',
    author: 'Eurostat',
    year: 2025,
    type: 'statistikk',
    description: 'Dokumenterer Norges prisposisjon sammenlignet med EU.',
    relevance: 'Internasjonal prissammenligning.',
    url: 'ec.europa.eu/eurostat'
  },
  {
    id: 'src-34',
    filename: 'civita-manifest-debatt.md',
    title: 'Samling av notater om dagligvare og konkurranse',
    author: 'Civita / Manifest Analyse',
    year: 2025,
    type: 'notat',
    description: 'Politiske ytterpunkter i debatten om importvern og markedsmakt.',
    relevance: 'Kartlegging av politiske posisjoner.',
  },
  {
    id: 'src-35',
    filename: 'fivh-etikk-2025.md',
    title: 'Bærekraftsstatus i dagligvarekjeden og effekten av Matsvinnloven',
    author: 'Framtiden i våre hender (FIVH)',
    year: 2025,
    type: 'rapport',
    description: 'Sosial bærekraft og etisk handel i matsystemet.',
    relevance: 'NGO-perspektiv på ansvar og transparens.',
    url: 'framtiden.no'
  },
  {
    id: 'src-36',
    filename: 'markedsundersokelser-status.md',
    title: 'Ny hjemmel for markedsetterforskning',
    author: 'Konkurransetilsynet',
    year: 2025,
    type: 'analyse',
    description: 'Status for nye regulatoriske verktøy for å tøyle markedsmakt.',
    relevance: 'Oversikt over nye inngrepsmuligheter.',
    url: 'konkurransetilsynet.no'
  },
  {
    id: 'src-37',
    filename: 'menon-emv-innovasjon.md',
    title: 'Egne merkevarer (EMV) og innovasjon',
    author: 'Menon Economics',
    year: 2024,
    type: 'rapport',
    description: 'Vurderer EMVs effekt på konkurranse og innovasjonstakt.',
    relevance: 'Motvekt til teorier om EMV som innovasjonsdreper.',
    url: 'menon.no'
  },
  {
    id: 'src-38',
    filename: 'uib-kjøpermakt.md',
    title: 'Buyer power and exclusion in vertically related markets',
    author: 'Tommy Staahl Gabrielsen m.fl.',
    year: 2025,
    type: 'analyse',
    description: 'Teoretisk rammeverk for kjøpermakt og forbrukervelferd.',
    relevance: 'Akademisk vurdering av markedsmaktens skadevirkninger.',
    url: 'uib.no/econ',
    doi: '10.1016/j.ijindorg.2014.11.001'
  },
  {
    id: 'src-39',
    filename: 'finsk-modell-hvk.md',
    title: 'National Emergency Supply Agency (NESA) / Huoltovarmuuskeskus (HVK)',
    author: 'Finske myndigheter',
    year: 2024,
    type: 'analyse',
    description: 'Gjennomgang av den finske modellen for beredskapslagring.',
    relevance: 'Benchmark for norsk beredskapsoppbygging.',
    url: 'nesafinland.fi'
  },
  {
    id: 'src-40',
    filename: 'nbs-systemkritikk.md',
    title: 'Plan for reell selvforsyning og jordbruksoppgjøret 2025',
    author: 'Norsk Bonde- og Småbrukarlag',
    year: 2025,
    type: 'rapport',
    description: 'Systemkritikk fra produsentens ståsted om selvforsyning og import.',
    relevance: 'Produsentperspektiv på matberedskap.',
    url: 'smabrukarlaget.no'
  },
  {
    id: 'src-41',
    filename: 'nordstad-tesen.md',
    title: 'Kritikk av det norske matsystemet og dagligvaremakta',
    author: 'Anders Nordstad',
    year: 2026,
    type: 'analyse',
    description: 'Systemkritiske teser om matpriser, ultraprosessering og selvforsyning.',
    relevance: 'Sentral systemkritisk stemme i offentligheten.',
  },
  {
    id: 'src-42',
    filename: 'prisjeger-saken.md',
    title: 'Vedtak om overtredelsesgebyr i dagligvaremarkedet',
    author: 'Konkurransetilsynet',
    year: 2024,
    type: 'lovverk',
    description: 'Juridisk vedtak om ulovlig informasjonsutveksling (prisjegere).',
    relevance: 'Dokumentasjon av svekket priskonkurranse.',
    url: 'konkurransetilsynet.no'
  },
  {
    id: 'src-43',
    filename: 'grensehandel-2025.md',
    title: 'Grensehandel — Statistikk over dagsturer til utlandet',
    author: 'Statistisk sentralbyrå (SSB)',
    year: 2025,
    type: 'statistikk',
    description: 'Dokumenterer lekkasje fra det norske matsystemet til Sverige.',
    relevance: 'Analyse av grensehandelens omfang og drivere.',
    url: 'ssb.no/grensehandel'
  },
  {
    id: 'src-44',
    filename: 'marginstudie-2024-del1.md',
    title: 'Lønnsomhet på virksomhetsnivå 2017–2022',
    author: 'Konkurransetilsynet',
    year: 2024,
    type: 'rapport',
    description: 'Historisk bevis på lønnsomhetsutvikling i verdikjeden.',
    relevance: 'Faktagrunnlag for debatt om superprofitt.',
    url: 'konkurransetilsynet.no'
  },
  {
    id: 'src-45',
    filename: 'oslo-economics-forsvar-2024.md',
    title: 'Konkurransen i dagligvaremarkedet – betydelig bedre enn sitt rykte!',
    author: 'Oslo Economics',
    year: 2024,
    type: 'rapport',
    description: 'Bransjebestilt forsvar for dagens markedskonkurranse.',
    relevance: 'Kjedenes argumentasjon i maktdebatten.',
    url: 'osloeconomics.no'
  },
  {
    id: 'src-46',
    filename: 'verdibutikker-utfordrere.md',
    title: 'Årsrapporter og markedsandel-analyser for Normal og Europris',
    author: 'Selskapenes kvartalsrapporter',
    year: 2025,
    type: 'årsrapport',
    description: 'Dokumenterer vekst for utfordrere utenfor det tradisjonelle triopolet.',
    relevance: 'Endringer i butikkstruktur og forbruksmønster.',
  },
  {
    id: 'src-47',
    filename: 'totalkalkylen-2024.md',
    title: 'Totalkalkylen for jordbruket (1A og 1B)',
    author: 'Budsjettnemnda for jordbruket',
    year: 2024,
    type: 'statistikk',
    description: 'Offisielle tall for bondens økonomiske realitet.',
    relevance: 'Grunnlag for statens jordbruksoppgjør.',
    url: 'regjeringen.no'
  },
  {
    id: 'src-48',
    filename: 'dlf-leverandør-2025.md',
    title: 'Dagligvareleverandørenes Forening (DLF) — Bransjeanalyse 2025',
    author: 'DLF Norge',
    year: 2025,
    type: 'rapport',
    description: 'Leverandørperspektiv på maktbalanse og logistikk-monopol.',
    relevance: 'Interesseorganisasjon for uavhengige merkevarer.',
    url: 'dlf.no'
  },
  {
    id: 'src-49',
    filename: 'eudr-norge-2025.md',
    title: 'EUs forordning om avskogingsfrie produkter (EUDR)',
    author: 'Miljødirektoratet',
    year: 2025,
    type: 'lovverk',
    description: 'Nye sporbarhetskrav for fôrimport og kjøttproduksjon.',
    relevance: 'Regulatorisk rammeverk for global bærekraft.',
    url: 'miljodirektoratet.no'
  },
  {
    id: 'src-50',
    filename: 'butikkstruktur-2024.md',
    title: 'Kartlegging av butikktetthet og sårbarhet i matforsyningen',
    author: 'Oslo Economics / NIBIO / NHH',
    year: 2024,
    type: 'analyse',
    description: 'Geografisk analyse av tilgang til mat og sårbarhet.',
    relevance: 'Vurdering av matørkener og butikktetthet.',
  },
  {
    id: 'src-51',
    filename: 'merkevarer-history.md',
    title: 'Historisk analyse av Stabburet/Toro-fusjonen og meierikonkurransen',
    author: 'Diverse kilder',
    year: 2025,
    type: 'analyse',
    description: 'Historisk oversikt over maktkampen mellom industri og kjeder.',
    relevance: 'Forståelse av merkevarenes strategiske posisjon.',
  },
  {
    id: 'src-52',
    filename: 'eiendomsmakt-lokal-konkurranse.md',
    title: 'Bruk av eiendom, reguleringsplaner og servitutter for å styre konkurranse',
    author: 'Tilsynsvedtak',
    year: 2025,
    type: 'lovverk',
    description: 'Dokumenterer fysiske etableringsbarrierer i lokale markeder.',
    relevance: 'Juridisk analyse av eiendomsmakt.',
  },
  {
    id: 'src-53',
    filename: 'matbors-historie.md',
    title: 'Effekten av medieovervåking på norsk dagligvare (2000–2025)',
    author: 'NHH-forskning',
    year: 2025,
    type: 'analyse',
    description: 'Historisk analyse av matbørsenes effekt på prisstrategier.',
    relevance: 'Atferdsøkonomisk blikk på priskonkurranse.',
  },
  {
    id: 'src-54',
    filename: 'reitan-2024-25.md',
    title: 'Reitan Retail Års- og ansvarsrapport 2024 / Foreløpige tall 2025',
    author: 'Reitan AS',
    year: 2025,
    type: 'årsrapport',
    description: 'Finansielle resultater for REMA 1000 og Reitan Retail.',
    relevance: 'Markedsandel og nordisk lavprisstrategi.',
    url: 'https://www.reitanretail.no/rapportering'
  },
  {
    id: 'src-55',
    filename: '01-primaerproduksjon.md',
    title: 'Nordisk Primaerproduksjon: Komparativ Analyse',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Kartlegging av landbruk, husdyrhold og planteproduksjon i alle 5 nordiske land. 610 linjer.',
    relevance: 'Verdikjedeledd 1: Produksjonsvolum, gardsbruk, kooperativer, okologisk andel.',
  },
  {
    id: 'src-56',
    filename: '02-foredling.md',
    title: 'Nordisk Foredlingsindustri: Komparativ Analyse',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Kartlegging av matforedlingsindustrien i alle 5 nordiske land. 353 linjer.',
    relevance: 'Verdikjedeledd 2: Kjott, meieri, korn, drikkevarer, vertikal integrasjon.',
  },
  {
    id: 'src-57',
    filename: '03-distribusjon-logistikk.md',
    title: 'Nordisk Distribusjon og Logistikk: Komparativ Analyse',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Kartlegging av grossist- og distribusjonsinfrastruktur i alle 5 nordiske land. 739 linjer.',
    relevance: 'Verdikjedeledd 3: Sentrallagre, kjoelekjede, havner, automatisering.',
  },
  {
    id: 'src-58',
    filename: '04-innsatsvarer.md',
    title: 'Nordiske Innsatsvarer og Oppstroms Forsyningskjede',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Kartlegging av gjodsel, for, fro, energi og maskiner for nordisk matproduksjon. 465 linjer.',
    relevance: 'Verdikjedeledd 0 (oppstroms): Importavhengigheter og sarbarhetsmatrise.',
  },
  {
    id: 'src-59',
    filename: '05-horeca.md',
    title: 'Nordisk HoReCa og Storhusholdning: Komparativ Analyse',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Kartlegging av foodservice-sektoren i alle 5 nordiske land. 403 linjer.',
    relevance: 'Verdikjedeledd 5: Grossister, storkjokken, skolemaltider, restauranter.',
  },
  {
    id: 'src-60',
    filename: '06-matsvinn-sirkulaer.md',
    title: 'Nordisk Matsvinn og Sirkulaer Okonomi: Komparativ Analyse',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Kartlegging av matsvinn og sirkularitet i hele verdikjeden i alle 5 land. 472 linjer.',
    relevance: 'Verdikjedeledd 7 (sirkulaert): Biogass, panteordninger, lovgivning, matdonasjon.',
  },
  {
    id: 'src-61',
    filename: '07-sjoemat.md',
    title: 'Nordisk Sjomatverdikjede: Komparativ Analyse',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Kartlegging av sjomatverdikjeden i hele Norden inkl. Faeroyene. 615 linjer.',
    relevance: 'Verdikjede sjoemat: Villfangst, akvakultur, foredling, for, eksport.',
  },
  {
    id: 'src-62',
    filename: '08-forbruk.md',
    title: 'Nordiske Forbrukermonstre og Matforbruk: Komparativ Analyse',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Kartlegging av forbruksmonstre og kostholdstrender i alle 5 land. 558 linjer.',
    relevance: 'Verdikjedeledd 6 (forbruker): Per capita forbruk, e-handel, grensehandel, REKO.',
  },
  {
    id: 'src-63',
    filename: '09-norsk-bedriftsdata.md',
    title: 'Norsk Bedriftsdata: Granulaer Kartlegging av 14 Nokkelaktorer',
    author: 'Food Systems 2026 Research / Bronnoydsundregistrene',
    year: 2026,
    type: 'analyse',
    description: 'Bedriftsdata for 14 norske mataktorer: org.nr, eierstruktur, aksjonaerer, styrer, regnskap, tilskudd, IP. Basert paa brreg.no API og offentlige kilder.',
    relevance: 'Granulaere selskapsdata: eierkonsentrasjon, interlocking directorates, krysseierskap, offentlig stotte.',
    url: 'https://data.brreg.no/enhetsregisteret/api'
  },
  {
    id: 'src-64',
    filename: '10-kryss-analyse.md',
    title: 'Kryssegment Verdikjedeanalyse: Maktkonsentrasjon og Systemrisiko',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Syntesedokument som analyserer maktkonsentrasjon, krysseierskap, flaskehalser, verdifordeling, systemrisiko og sirkulaerokonomi-gaps pa tvers av 9 verdikjedeledd.',
    relevance: 'Hovedkonklusjoner: Norge hoeyest HHI (~3400) i Europa, 7 kritiske flaskehalser, BAMA-nettverket unik maktposisjon.',
  },
  {
    id: 'src-65',
    filename: 'nou-stortingsdok-juridisk.md',
    title: 'NOU-er, Stortingsdokumenter og Juridiske Kilder',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: '10 primaerkilder: NOU 2013:6, Meld. St. 9/11/4, Prop. 33 L, markedsetterforskning, lov om god handelsskikk, konkurranseloven, finsk 4a, EU UTP.',
    relevance: 'Regulatorisk rammeverk og politisk kontekst for norsk matsystem.',
    url: 'https://www.regjeringen.no/'
  },
  {
    id: 'src-66',
    filename: 'konkurransetilsyn-konsulent.md',
    title: 'Konkurransemyndigheter og Konsulentrapporter: Kildebibliotek',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: '12 kilder fra Konkurransetilsynet, Dagligvaretilsynet, KFST, SOA, Menon og Oslo Economics. Inkl. Prisjeger-vedtaket (4,9 mrd), marginstudien, innkjoepspriskartlegging.',
    relevance: 'Kvantitativt bevisgrunnlag for markedsmakt og priskonkurranse. Bestiller-perspektiv avslorer systematisk bias.',
  },
  {
    id: 'src-67',
    filename: 'bransje-statistikk-beredskap.md',
    title: 'Bransje-, Statistikk- og Beredskapskilder',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: '16 kilder: Virke, NHO Mat og Drikke, Bondelaget, Sjoemat Norge, SSB, Eurostat, FAO, OECD, NIBIO, DSB, HVK Finland. 30+ noekkelmetrikker.',
    relevance: 'Kvantitativ evidensbase: selvforsyningsgrad 34,9%, importavhengighet 125,5 mrd, Finlands 8,5 mnd kornlager vs Norge null.',
  },
  {
    id: 'src-68',
    filename: 'akademia-dyp-research.md',
    title: 'Dyp Akademisk Research: NHH FOOD, SIFO, UiB/BECCLE, Internasjonalt',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: '27 akademiske kilder: Steen/Foros (NHH FOOD), Gabrielsen (UiB), SIFO dyrtid/referansebudsjett, Dobson (buyer power), OECD competition in food. Matfattigdom, EMV 20%, co-location.',
    relevance: 'Akademisk evidensbase: prismekanismer, kjopermakt, matfattigdom (1 av 12 husholdninger), sortiment som skjult markedsmakt.',
  },
  {
    id: 'src-69',
    filename: 'tenketanker-ngo.md',
    title: 'Tenketanker, NGO-er og Sivilsamfunn: Politisk Landskapskart',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: '17 kilder: Civita/Agenda/Manifest (politisk spekter), FIVH/Naturvernforbundet/Matvalget (miljo), SRC/Nordic Council/EAT/IPES-Food (systemnivaet), BERAS/DNVA (nordisk).',
    relevance: 'Politisk landskap fra fri-marked (Civita) til systemtransformasjon (IPES-Food). DNVA: Norge mangler nasjonal matpolitikk. EAT legges ned 2026.',
  },
  {
    id: 'src-70',
    filename: 'sirkularitet-dyp.md',
    title: 'Sirkularitet og Matsvinn: Dyp Research med Biogass-gap-analyse',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: '22 kilder: Matvett matsvinn 407k tonn, matsvinnloven 2026, biogass-gap 11,6x (DK 8 TWh vs NO 0,7 TWh), fosfor-gjenvinning HIAS, insektprotein, Wageningen cascading.',
    relevance: 'Konkret transformasjonsspor: 100-160 nye biogassanlegg, 15-25 mrd NOK investering, 5 virkemidler for aa lukke gapet med Danmark.',
  },
  {
    id: 'src-71',
    filename: 'meeting-4-research-focus.md',
    title: 'Research Focus Report: Meeting-4',
    author: 'Food Systems 2026 Research',
    year: 2026,
    type: 'analyse',
    description: 'Destillering av 27+ forskningstraader fra meeting-4 (strategisk ledergruppe 16. mars). 7 seksjoner: hypoteser, konseptuelle gap, datainfrastruktur, aktoerer, policy, metodikk, prioriteringsmatrise med 20 punkter.',
    relevance: 'Styringsdokument for forskningsprioriteringer mars-juni 2026. Identifiserer gap i eiendomsmodell, food desert-analyse, sirkularitetskobling og aktoerregister.',
  },
  {
    id: 'src-72',
    filename: 'sirkulaer-matsystem-rammeverk.md',
    title: 'WUR White Paper: Circular Food Systems around the world',
    author: 'Bonilla Cedrez et al. (WUR)',
    year: 2023,
    type: 'forskning',
    description: 'Wageningen-rammeverk med 4 operative prinsipper for sirkulaere matsystemer og biomassehierarki.',
    relevance: 'Grunnlag for operativt kriteriesett i sirkularitetsanalyse.',
    publisher: 'Wageningen University & Research',
    url: 'https://doi.org/10.18174/638397',
    doi: '10.18174/638397',
  },
  {
    id: 'src-73',
    filename: 'van-zanten-nature-food-2023.md',
    title: 'Circularity in Europe strengthens the sustainability of global food systems',
    author: 'van Zanten et al.',
    year: 2023,
    type: 'forskning',
    description: 'Nature Food-artikkel som modellerer europeisk sirkularitet og viser at CFS reduserer globalt arealbruk 71% og GHG 29%.',
    relevance: 'Kvantifiserer nordisk sirkularitetspotensial.',
    publisher: 'Nature Food',
    url: 'https://www.nature.com/articles/s43016-023-00734-9',
    doi: '10.1038/s43016-023-00734-9',
  },
  {
    id: 'src-74',
    filename: 'eat-lancet-2025.md',
    title: 'EAT-Lancet Commission 2.0: Food in the Anthropocene',
    author: 'EAT-Lancet Commission',
    year: 2025,
    type: 'forskning',
    description: 'Oppdatert planetaert referansekoshold med sterkere vekt paa regenerativt landbruk og sirkulaer biomasse.',
    relevance: 'Global referanseramme for nordisk matsystemtransformasjon.',
    publisher: 'The Lancet',
    url: 'https://eatforum.org/eat-lancet-commission/',
  },
  {
    id: 'src-75',
    filename: 'jrc-spp-2025.md',
    title: 'JRC SPP 2025: Green Public Procurement Criteria for Food and Catering',
    author: 'Joint Research Centre (EU)',
    year: 2025,
    type: 'rapport',
    description: 'EUs groenne innkjoepskriterier for mat: oekologisk, lavutslipp, redusert matsvinn i offentlige kontrakter.',
    relevance: 'Operativt rammeverk for offentlig innkjoep som policy-verktoy.',
    publisher: 'European Commission Joint Research Centre',
    url: 'https://publications.jrc.ec.europa.eu/repository/handle/JRC144579',
    doi: '10.2760/9479564',
  },
  {
    id: 'src-76',
    filename: 'nkj-white-paper-2024.md',
    title: 'NKJ White Paper: Nordic Sustainable Food Systems — 12 intervensjonspunkter',
    author: 'Nordisk komite for jordbruksforskning (NKJ)',
    year: 2024,
    type: 'rapport',
    description: 'Identifiserer 12 nordiske intervensjonspunkter for matsystemtransformasjon inkl. 4 pilarer.',
    relevance: 'Nordisk-spesifikt rammeverk for transformasjon.',
    publisher: 'Nordisk komite for jordbruksforskning',
    url: 'https://nordicagriresearch.org/wp-content/uploads/2024/11/2-White-Paper-on-Nordic-Sustainable-Food-Systems.pdf',
  },
  {
    id: 'src-77',
    filename: 'halseth-nhh-2023.md',
    title: 'Lokal HHI i norsk dagligvare: median 1.0 paa postnummernivaet',
    author: 'Stroem Halseth (NHH)',
    year: 2023,
    type: 'forskning',
    description: 'Kartlegger lokal markedskonsentrasjon i Norge paa postnummernivaet. Median HHI=1.0 (monopol).',
    relevance: 'Foerste granulare HHI-analyse av norsk dagligvare.',
    publisher: 'Norges Handelshoyskole / CRESSE',
    url: 'https://www.cresse.info/wp-content/uploads/2023/09/2023_ps13_pa2_Strom-Halseth.pdf',
  },
  {
    id: 'src-78',
    filename: 'konkurrensverket-2024-4.md',
    title: 'Naermaste konkurrent-analys: 290 kommuner',
    author: 'Konkurrensverket (Sverige)',
    year: 2024,
    type: 'rapport',
    description: 'Svensk analyse av lokal konkurranse: 102 av 290 kommuner mangler discounter.',
    relevance: 'Komparativt perspektiv paa lokal food access i Norden.',
    url: 'https://www.konkurrensverket.se/publikationer/',
  },
  {
    id: 'src-79',
    filename: 'kfst-fusjon-2024.md',
    title: 'KFST fusjonsanalyse Salling/Coop 2024-2025 (drive-time HHI)',
    author: 'KFST (Danmark)',
    year: 2024,
    type: 'rapport',
    description: 'Dansk fusjonsanalyse med drive-time HHI-metodikk for dagligvare.',
    relevance: 'Metodisk referanse for nordisk HHI-beregning.',
  },
  {
    id: 'src-80',
    filename: 'cdrc-priority-places.md',
    title: 'CDRC Priority Places for Food Index v2.1',
    author: 'Consumer Data Research Centre (UK)',
    year: 2024,
    type: 'datasett',
    description: '7-domene komposittindeks for food access i UK. Kombinerer GIS, kvalitet og oekonomi.',
    relevance: 'Metodisk benchmark for nordisk food desert-analyse.',
    url: 'https://data.cdrc.ac.uk/',
  },
  {
    id: 'src-81',
    filename: 'statistics-finland-hbs-2012.md',
    title: 'Statistics Finland HBS 2012: Butikkavstand',
    author: 'Statistics Finland',
    year: 2012,
    type: 'datasett',
    description: 'Finsk husholdningsundersoekelse: median 700m til naermeste dagligvarebutikk.',
    relevance: 'Finsk referansepunkt for food access.',
    url: 'https://stat.fi/til/ktutk/2012/ktutk_2012_2014-05-26_tie_001_en.html',
  },
  {
    id: 'src-82',
    filename: 'ecr-dagligvarukartan-2024.md',
    title: 'ECR Dagligvarukartan 2024/2025',
    author: 'DLF/Delfi',
    year: 2025,
    type: 'rapport',
    description: 'Arlig markedsandelskartlegging for svensk dagligvare.',
    relevance: 'Oppdaterte svenske markedsandeler og CR3.',
    url: 'https://dlf.se/download/1167-E8CD2BD7C83DEB69C493BFA61DBE64A0/dagligvarukartan2024-PPT.pdf',
  },
  {
    id: 'src-83',
    filename: 'pty-grocery-2024.md',
    title: 'PTY Finnish Grocery Trade Statistics 2024/2025',
    author: 'Paivittaistavarakauppa ry (PTY)',
    year: 2025,
    type: 'rapport',
    description: 'Offisielle finske dagligvaretall: S Group 48.8%, K Group 33.7%.',
    relevance: 'Finsk markedsstruktur og duopoldata.',
  },
  {
    id: 'src-84',
    filename: 'bibliotek/media/snapshots/dk-usda-gain-retail-2025.md',
    title: 'USDA GAIN Retail Foods Annual: Denmark DA2025-0002',
    author: 'USDA Foreign Agricultural Service',
    year: 2025,
    type: 'rapport',
    description: 'Offisiell USDA/FAS GAIN-rapport publisert i 2025 med dansk dagligvaremarked og 2024-markedsdata.',
    relevance: 'Oppdatert dansk markedsstruktur inkl. Aldi-exit.',
    publisher: 'USDA Foreign Agricultural Service',
    url: 'https://apps.fas.usda.gov/newgainapi/api/Report/DownloadReportByFileName?fileName=Retail+Foods+Annual_The+Hague_Denmark_DA2025-0002.pdf',
  },
  {
    id: 'src-85',
    filename: 'usda-gain-iceland-exporter-guide-2023.md',
    title: 'USDA GAIN Iceland Exporter Guide',
    author: 'USDA Foreign Agricultural Service',
    year: 2023,
    type: 'rapport',
    description: 'Offisiell USDA/FAS GAIN Exporter Guide for Island. Brukes som sekundar kryssjekk for islandsk dagligvarestruktur og Kronan/Festi-markedsdata.',
    relevance: 'Islandsk markedsstruktur og sammenliknbare markedsandelsdata.',
    publisher: 'USDA Foreign Agricultural Service',
    url: 'https://apps.fas.usda.gov/newgainapi/api/Report/DownloadReportByFileName?fileName=Iceland+Exporter+Guide_The+Hague_Iceland_IC2023-0001.pdf',
  },
  {
    id: 'src-86',
    filename: 'nhh-food-steen-2024.md',
    title: 'NHH FOOD: Prof. Frode Steen markedsanalyse april 2024',
    author: 'Prof. Frode Steen (NHH FOOD)',
    year: 2024,
    type: 'forskning',
    description: 'Akademisk analyse av norsk dagligvaremarked med HHI-beregning og prismekanismer.',
    relevance: 'Akademisk validering av markedskonsentrasjon.',
    url: 'https://www.nhh.no/en/research-centres/food/food-news/2024/all-retail-sectors-are-highly-concentrated/',
  },
  {
    id: 'src-87',
    filename: 'halseth-phd-2024.md',
    title: 'Competition and Grocery Retail Formats: CID-analyse',
    author: 'Stroem Halseth (NHH)',
    year: 2024,
    type: 'forskning',
    description: 'PhD-avhandling: Coop/ICA rebranding av 554 butikker → 7-12.9% salgsfall for eksisterende discountere.',
    relevance: 'Empirisk analyse av konkurranse ved formatendring.',
  },
  {
    id: 'src-88',
    filename: 'eriksson-phd-2015.md',
    title: 'Supermarket food waste: Prevention and management at the retail stage',
    author: 'Mattias Eriksson (SLU)',
    year: 2015,
    type: 'forskning',
    description: 'PhD SLU: 6-butikk studie av matsvinn i svensk dagligvare, 1.2% av omsetning.',
    relevance: 'Pionerarbeid paa matsvinnkvantifisering i svensk dagligvare.',
  },
  {
    id: 'src-89',
    filename: 'sundin-phd-2024.md',
    title: 'Sustainability of food waste prevention',
    author: 'Nils Sundin (SLU)',
    year: 2024,
    type: 'forskning',
    description: 'PhD SLU: 32% husholdningsavfall forebyggbart, men kun 0.5% av nasjonale utslipp.',
    relevance: 'Nyanserer matsvinndebatt med faktisk klimaeffekt.',
    doi: '10.54612/a.2fjqatdg6h',
  },
  {
    id: 'src-90',
    filename: 'lehtokunnas-phd-2023.md',
    title: 'Enacting a Circular Economy: An Ethnography of Multiple Possible Futures',
    author: 'Taru Lehtokunnas (Tampere)',
    year: 2023,
    type: 'forskning',
    description: 'PhD Tampere: Etnografi av sirkulaer oekonomi i praksis, multiple framtidsscenarier.',
    relevance: 'Kvalitativ motpol til kvantitative sirkularitetsmaalet.',
  },
  {
    id: 'src-91',
    filename: 'matsvinnutvalget-2024.md',
    title: 'Matsvinnutvalgets rapport 2024: 75% reduksjon mulig',
    author: 'Matsvinnutvalget',
    year: 2024,
    type: 'rapport',
    description: 'Ekspertutvalg konkluderer at 75% reduksjon av matsvinn er mulig — langt over SDG 12.3 (50%).',
    relevance: 'Styrker ambisjonsnivaaet for norsk matsvinninnsats.',
  },
  {
    id: 'src-92',
    filename: 'nmr-vision-2030.md',
    title: 'Nordic Bioeconomy Programme: 15 Action Points for Sustainable Change',
    author: 'Nordic Council of Ministers',
    year: 2018,
    type: 'rapport',
    description: 'Nordisk ministerraads biooekonomiprogram for konkurransedyktige biobaserte naeringer, baerekraftig ressursforvaltning, robuste oekosystemer og inkluderende oekonomisk utvikling.',
    relevance: 'Primaer policykilde for biooekonomi- og sidestroemssporet i Nordic Vision 2030-arbeidet.',
    url: 'https://www.norden.org/en/publication/nordic-bioeconomy-programme',
    publisher: 'Nordic Council of Ministers',
  },
  {
    id: 'src-93',
    filename: 'oecd-flw-2025.md',
    title: 'Beyond FLW Reduction Targets: Measuring and Valuing Food Loss and Waste',
    author: 'OECD',
    year: 2025,
    type: 'rapport',
    description: 'OECD-rapport om maalemetoder og verdsetting av matsvinn — utover SDG-maal.',
    relevance: 'Metodisk referanse for matsvinnmaaling.',
    url: 'https://doi.org/10.1787/59cf6c95-en',
    doi: '10.1787/59cf6c95-en',
  },
  {
    id: 'src-94',
    filename: 'greenpeace-feeding-monster-2021.md',
    title: 'Feeding a Monster: Vest-afrikansk fiskemel i norsk laksefor',
    author: 'Greenpeace / Changing Markets',
    year: 2021,
    type: 'rapport',
    description: 'Dokumenterer 500 000+ tonn smaapelagisk fisk fra Vest-Afrika til EU aarlig, inkl. norsk laksenaering.',
    relevance: 'Sentralt dokument om matsikkerhetskonflikten i sjomatfor.',
    url: 'https://www.greenpeace.org/',
  },
  {
    id: 'src-95',
    filename: 'feedback-blue-empire-2024.md',
    title: 'Blue Empire: Matsikkerhetskonflikt norsk laksefor og Vest-Afrika',
    author: 'Feedback / Greenpeace Africa',
    year: 2024,
    type: 'rapport',
    description: '123-144K tonn Vest-Afrika smaapelagisk fisk til norsk for i 2020 — 2.5-4M menneskers matforbruk.',
    relevance: 'Oppdatert kvantifisering av Vest-Afrika-konflikten.',
    url: 'https://foodrise.org.uk/blue-empire-how-your-supermarket-salmon-is-impacting-communities-in-west-africa/',
  },
  {
    id: 'src-96',
    filename: 'ravareloeftet-2024.md',
    title: 'Raavareloeftet 2.0 (Bellona + Sjoemat Norge + forselskaper)',
    author: 'Bellona Foundation / Sjoemat Norge',
    year: 2024,
    type: 'initiativ',
    description: 'Industriinitiativ: 0.4% → 25% nye raavarer i norsk laksefor innen 2030.',
    relevance: 'Kritisk transformasjonsvindu for norsk sjomatfor.',
    url: 'https://bellona.no/project/ravareloftet',
  },
  {
    id: 'src-97',
    filename: 'skretting-sustainability-2024.md',
    title: 'Skretting Sustainability Report 2024: MicroBalance FLX',
    author: 'Skretting (Nutreco/SHV)',
    year: 2024,
    type: 'rapport',
    description: 'Foerste kommersielle laksefor helt uten fiskemel (MicroBalance FLX).',
    relevance: 'Teknologisk gjennombrudd i forsirkularitet.',
    url: 'https://www.skretting.com/en-es/sustainability/sustainability-reporting/',
  },
  {
    id: 'src-98',
    filename: 'nordicfeed-nordforsk.md',
    title: 'NordicFeed EUR 10M NordForsk-prosjekt: Gjaer/soppprotein',
    author: 'NMBU / NordForsk',
    year: 2025,
    type: 'forskning',
    description: 'Nordisk forskningsprosjekt paa gjaer- og soppbasert protein fra skog- og matsidestroemmer.',
    relevance: 'Novel ingrediens med nordisk raavarebasis.',
    url: 'https://www.nmbu.no/en/research/projects/nordicfeed',
  },
  {
    id: 'src-99',
    filename: 'green-platform-mikroalger.md',
    title: 'Green Platform NOK 93.3M: Mikroalger CO2-basert',
    author: 'Nofima / SINTEF / UiT / Finnfjord',
    year: 2025,
    type: 'forskning',
    description: 'Norsk forskningsprosjekt: dyrke omega-3-rike alger fra industrielt CO2-utslipp for laksefor.',
    relevance: 'Sirkulaer utnyttelse av industriutslipp til forproduksjon.',
    url: 'https://sa.uit.no/nyheter/artikkel?p_document_id=745023',
  },
  {
    id: 'src-100',
    filename: 'Strategisk ledergruppe Marked 16 mars 2026.md',
    title: 'Strategisk ledergruppe Marked 16. mars 2026',
    year: 2026,
    type: 'transkripsjon',
    description: 'Ratranskripsjon fra strategisk ledergruppemote med roller, leveranser, nordisk retning og Food/Cities-kobling.',
    relevance: 'Primarunderlag for meeting-4 og den avledede research focus-rapporten.',
  },
  {
    id: 'src-101',
    filename: 'coffee-forest-prd.md',
    title: 'Coffee & Forest EUDR Compliance Platform PRD',
    author: 'Natural State / Fuglen Coffee',
    year: 2026,
    type: 'arbeidsdok',
    description: 'Product Requirements Document for EUDR compliance platform: supply chain traceability, satellite deforestation layers, Due Diligence Statements for Fuglen Coffee.',
    relevance: 'Verdikjede-sporbarhet, EUDR-regulering, deforestation-nexus relevant for fiskefôr-hypotese.',
  },
  {
    id: 'src-102',
    filename: 'coffee-forest-eudr-research.md',
    title: 'EUDR Research Review: Regulatory Landscape and Compliance',
    author: 'Natural State Research',
    year: 2026,
    type: 'analyse',
    description: 'Forskningsoversikt over EUs avskogingsforordning med fokus på kaffeimport og compliance-krav.',
    relevance: 'Regulatorisk kontekst for EUDR som påvirker norsk matimport og fôrkjeder.',
  },
  {
    id: 'src-103',
    filename: 'ni-soknad-ncc-fase-2.md',
    title: 'Søknad NCC fase 2 til Nordic Innovation',
    author: 'Natural State',
    year: 2026,
    type: 'soknad',
    description: 'Nyeste NI-søknad for Nordic Circular Construction med oppdatert prosjektbeskrivelse, konsortium og Nordic Material Intelligence-rammeverk.',
    relevance: 'Søsterprosjekt-kontekst, delt NCH-metodikk og nordisk samarbeidsmodell.',
  },
  {
    id: 'src-104',
    filename: 'biosirkel-studietur-zero-waste-scotland.md',
    title: 'Biosirkel studietur-møte Zero Waste Scotland',
    author: 'Biosirkel / Zero Waste Scotland',
    year: 2025,
    type: 'notat',
    description: 'Møtenotater fra planlegging av studietur til Skottland: akvakulturinnovasjon, industriell symbiose, alternative fiskefôr, bioparker, biogass, algedyrking.',
    relevance: 'Direkte kobling til sirkulær bioøkonomi, fiskefôr-transformasjon og nordisk-skotsk samarbeid.',
  },
  {
    id: 'src-105',
    filename: 'nordic-house-mote.md',
    title: 'Nordic House møte — NCH nordisk-baltisk strategi',
    author: 'Nordic Circular Hotspot',
    year: 2026,
    type: 'notat',
    description: 'Strategimøte om NCH nordisk-baltisk samarbeid. Bekrefter Mat og matsystemer som aktiv transition group. RIMI som baltisk dagligvarekobling. Kulturforskjeller i nordisk sirkulær økonomi.',
    relevance: 'Bekrefter food systems som NCH-prioritet, kartlegger nordisk-baltisk ekspansjon og sektortilnærming.',
  },
  {
    id: 'src-106',
    filename: 'nch-hovedside.md',
    title: 'Nordic Circular Hotspot — hovedside og transition groups',
    author: 'Nordic Circular Hotspot',
    year: 2026,
    type: 'strategi',
    description: '6 transition groups inkl. Mat og bioøkonomi (matsvinn, bioprodukter, sirkulære verdikjeder). Nordisk-baltisk ekspansjon, 10-årsplan, events 2026-2029.',
    relevance: 'Overordnet NCH-kontekst og posisjonering av mat/bioøkonomi som transition group #3.',
  },
  {
    id: 'src-107',
    filename: 'nch-funding-map.md',
    title: 'NCH Funding Map — finansieringsverktøy',
    author: 'Natural State',
    year: 2026,
    type: 'strategi',
    description: 'Internt funding-verktøy med 9958 grants, 250 ordninger. Dekker NFR, Horizon Europe, SkatteFUNN, Doffin. NCH-strategi: NI 5M NOK, Interreg OKS, Horizon, Norden.org.',
    relevance: 'Finansieringskontekst for Food Systems-prosjektet og NCH-porteføljen.',
  },
  {
    id: 'src-108',
    filename: 'biosirkel-prosjekt.md',
    title: 'Biosirkel — prosjektside',
    author: 'Natural State',
    year: 2026,
    type: 'notat',
    description: 'Prosjekthub for Biosirkel-initiativet under Natural States markedsutvikling. Status: Aktivt. Prosjektnummer 78.',
    relevance: 'Organisatorisk kontekst for biosirkel som NCH-aktivitet.',
  },
  {
    id: 'src-109',
    filename: 'fuglen-sources.md',
    title: 'Fuglen Coffee — kildeliste og leverandørkjede',
    author: 'Coffee&Forest Research',
    year: 2026,
    type: 'arbeidsdok',
    description: 'Kildeliste fra Fuglen Coffee-prosjektet med leverandørdata og compliance-referanser.',
    relevance: 'Sporbarhet i kaffeverdikjeden, kobling til EUDR og norsk matimport.',
  },
  {
    id: 'src-110',
    filename: 'SEC-MAT-01-regulering-matsvinn.md',
    title: 'Sektorkartlegging: Regulering og matsvinn',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Kartlegging av matsvinnregulering i Norden: bransjeavtaler, EU-krav, matdonasjonslovgivning, sektoransvar.',
    relevance: 'Regulatorisk rammeverk for matsvinn — nøkkeldata for policy-analyse.',
  },
  {
    id: 'src-111',
    filename: 'SEC-MAT-02-sirkuaere-prosesser-biookonomi.md',
    title: 'Sektorkartlegging: Sirkulære prosesser og bioøkonomi',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Sirkulære matprosesser: sidestrømsvalorisering, biogass fra matavfall, insektprotein, fermentering, nordiske eksempler.',
    relevance: 'Teknologiske muligheter for sirkulær verdiskaping i matsektoren.',
  },
  {
    id: 'src-112',
    filename: 'SEC-MAT-03-emballasje-ppwr.md',
    title: 'Sektorkartlegging: Emballasje og PPWR',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'EU PPWR-forordningen og emballasje i matindustrien: gjenbrukskrav, resirkuleringsmål, nordiske pilotprosjekter.',
    relevance: 'Regulatorisk trykk på matemballasje — sentral for dagligvarekjedenes omstilling.',
  },
  {
    id: 'src-113',
    filename: 'SEC-MAT-REG-01-matsvinn-lovverk.md',
    title: 'Matsvinn detaljert lovverk',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Detaljert gjennomgang av lovverk knyttet til matsvinn: EU matsvinnforordning, norsk forskrift, rapporteringskrav, bransjeavtale mot matsvinn.',
    relevance: 'Juridisk grunnlag for matsvinntiltak og måling.',
  },
  {
    id: 'src-114',
    filename: 'SEC-MAT-REG-02-emballasje-matsektor.md',
    title: 'Emballasje i matsektoren — detalj',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Detaljanalyse av emballasjeregulering spesifikt for matsektoren: Grønt Punkt, retursystemer, SUP-direktiv, nordisk harmonisering.',
    relevance: 'Spesifikk emballasjeregulering for matindustrien.',
  },
  {
    id: 'src-115',
    filename: 'SEC-MAT-REG-03-danmark-co2-avgift.md',
    title: 'Danmark CO2-avgift på landbruk',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Analyse av dansk historisk CO2-avgift på landbruk (vedtatt 2024): 300 DKK/tonn CO2e fra 2030, 750 DKK fra 2035. Konsekvenser for nordisk matproduksjon.',
    relevance: 'Nordisk policy-pionér — benchmark for norsk landbrukspolitikk.',
  },
  {
    id: 'src-116',
    filename: 'SEC-MAT-KOST-01-nordisk-kosthold-beredskap.md',
    title: 'Nordisk kosthold og beredskap',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Analyse av nordisk kostholdspolitikk og matberedskap: NNR2023, selvforsyningsgrad, nordisk kostholdsmønster, beredskapslagre.',
    relevance: 'Ernæringssikkerhet og beredskap som policy-dimensjon i matsystemet.',
  },
  {
    id: 'src-117',
    filename: 'SEC-MAT-TEK-01-matteknologi.md',
    title: 'Fremtidens matteknologi',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Kartlegging av fremtidens matteknologi: presisjonsfermentering, cellulært landbruk, vertikal dyrking, AI i matproduksjon, nordiske startups.',
    relevance: 'Teknologisk disrupsjonspotensial i nordisk matsektor.',
  },
  {
    id: 'src-118',
    filename: 'SEC-MAT-TEK-02-biotech-proteiner.md',
    title: 'Biotech og fremtidens proteiner',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Alternative proteiner i Norden: plantebasert, insektprotein, mikrobielt protein, microalger. Regulatorisk status og markedspotensial.',
    relevance: 'Proteintransformasjon som nøkkeldriver i nordisk matomstilling.',
  },
  {
    id: 'src-119',
    filename: 'SEC-MAT-PROD-01-havbruk-for.md',
    title: 'Nordisk havbruk og fôr',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Analyse av nordisk havbruk og fôrverdikjede: soyaavhengighet, alternative fôrkilder (insekt, mikroalger, encelleprotein), bærekraftssertifisering.',
    relevance: 'Sentral for sjømatselskapene i databasen (Mowi, SalMar, Lerøy, Cermaq).',
  },
  {
    id: 'src-120',
    filename: 'SEC-MAT-PROD-02-regenerativt-landbruk.md',
    title: 'Regenerativt landbruk i Norden',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Regenerativt landbruk i nordisk kontekst: karbonfangst i jord, redusert jordbearbeiding, agroskogbruk, norske og svenske pilotprosjekter.',
    relevance: 'Produksjonsomstilling i primærnæringen — kobling til Felleskjøpet, Nortura.',
  },
  {
    id: 'src-121',
    filename: 'SEC-MAT-PROD-03-blaa-biookonomi.md',
    title: 'Blå bioøkonomi — teknisk detalj',
    author: 'Bærekraft Kartlegging Prosjekt',
    year: 2025,
    type: 'analyse',
    description: 'Teknisk dybdeanalyse av blå bioøkonomi: tang/tare-industri, sjømatrestråstoff, marin bioprospektering, nordiske verdikjeder.',
    relevance: 'Sirkularitet i sjømatverdikjeden — kobling til Arctic Cluster Team, Nofima.',
  },
  {
    id: 'src-122',
    filename: 'SA-02-mat-og-biomasse.md',
    title: 'Sektoranalyse: Mat og biomasse (Circular Cities)',
    author: 'Circular Cities 2026 Research',
    year: 2025,
    type: 'analyse',
    description: '382-linjers sektoranalyse av mat/biomasse-verdikjeder i alle 5 nordiske land. Matsvinn >3.6M tonn/år, biogass (DK 8.1 TWh vs NO 0.47 TWh), REKO-ringer.',
    relevance: 'Gullgruven — overlapper alle 14 selskaper i Food Systems DB. Nordisk komparativ matdata.',
  },
  {
    id: 'src-123',
    filename: 'C02-mat-biomasse-biogass.md',
    title: 'Kommunale food-circular cases (Circular Cities)',
    author: 'Circular Cities 2026 Research',
    year: 2025,
    type: 'analyse',
    description: '14 dokumenterte kommunale food-circular cases: Den Magiske Fabrikken, Billund BioRefinery, REKO-ringer (274 ringer, 786k forbrukere).',
    relevance: 'Kommunale best practices for matavfall→biogass→biogjødsel→jordbruk-loop.',
  },
  {
    id: 'src-124',
    filename: 'external/circular-cities/15-nordic-policy-landscape.md',
    title: 'Nordisk policy-landskap (Circular Cities)',
    author: 'Circular Cities 2026 Research',
    year: 2025,
    type: 'analyse',
    description: '447-linjers nordisk policy-syntese. Mat = 1 av 7 CEAP-prioriteter. Dekker EU Taxonomy, CSRD, nordiske handlingsplaner.',
    relevance: 'Overordnet nordisk policy-rammeverk med mat som prioritert sektor.',
  },
  {
    id: 'src-125',
    filename: 'external/circular-cities/07-horizon-europe-call-analysis.md',
    title: 'Horizon Europe-kall: Cluster 6 Food/Bioeconomy (Circular Cities)',
    author: 'Circular Cities 2026 Research',
    year: 2025,
    type: 'analyse',
    description: 'Analyse av Horizon Europe Cluster 6-kall. CIRCBIO-09: EUR 12M for food security + bioeconomy + climate. Direkte finansieringsmulighet.',
    relevance: 'Konkret Horizon-kall relevant for Food Systems 2026-prosjektet.',
  },
  {
    id: 'src-126',
    filename: 'external/circular-cities/19-nordic-added-value.md',
    title: 'Nordisk merverdi og NCH-portefølje (Circular Cities)',
    author: 'Circular Cities 2026 Research',
    year: 2025,
    type: 'analyse',
    description: 'NCH 4 transition groups: Cities, Corporations, Food, Textile. Food Systems og Circular Cities som søsterprosjekter med delt KPI-rammeverk.',
    relevance: 'Bekrefter Food Systems som NCH-porteføljeelement med nordisk merverdi.',
  },

  // ═══ Forskningsrunde 2026-04-20 — 10 dybderapporter fra Food Research Process ═══

  {
    id: 'src-127',
    filename: 'evidensnotat-2026-04-20.md',
    title: 'Evidensnotat for Food Systems 2026',
    author: 'Food Research Process',
    year: 2026,
    type: 'analyse',
    description: 'Metodologisk notat som etablerer STROBE+GRADE-rammeverk for evidensregister, kildeinventar og klaimgradering i FS2026-arbeidet. Definerer 8 prioriterte metadatafelt og tre epistemiske kategorier.',
    relevance: 'Rammesetter for hvordan alle andre dokumenter i forskningsrunden skal graderes og brukes i hvitbokscopy.',
  },
  {
    id: 'src-128',
    filename: 'eiendomsmakt-dagligvaremarkedet-norden-2026-04-20.md',
    title: 'Eiendomsmakt i dagligvaremarkedet i Norge og Norden',
    author: 'Food Research Process',
    year: 2026,
    type: 'analyse',
    description: 'Dybdeanalyse av hvordan eiendom (servitutter, eksklusive leieavtaler, internleie, sale-leaseback) fungerer som strukturell konkurransebarriere i nordisk dagligvare. Inkluderer 350+ registrerte negative servitutter, NorgesGruppen internleie NOK 168m (2024), Reitan Eiendom 2,077 mill kvm.',
    relevance: 'Primaert grunnlagsdokument for eiendomssporet. Peker paa eksklusive leieavtaler som neste regulatoriske front.',
  },
  {
    id: 'src-129',
    filename: 'makt-fryktkultur-enforcement-2026-04-20.md',
    title: 'Makt, fryktkultur og svak enforcement i norsk og nordisk dagligvare',
    author: 'Food Research Process',
    year: 2026,
    type: 'analyse',
    description: 'Analyse av hvorfor Lov om god handelsskikk leverer under potensial: narrow lovdesign, dialogbasert handheving, strukturell avhengighet, fryktdrevet under-rapportering. Dokumenterer 0 vedtak om lovbrudd siden 2020, 13-17% muntlige sideavtaler, >1/3 delistet uten saklig grunn.',
    relevance: 'Rammer overgangen 30. april 2026 (til Konkurransetilsynet) og peker paa hva som maa endres parallellt for at overflytting skal gi effekt.',
  },
  {
    id: 'src-130',
    filename: 'framstillinger-mat-makt-beredskap-2026-04-20.md',
    title: 'Framstillinger av mat, makt og beredskap i norsk offentlighet',
    author: 'Food Research Process',
    year: 2026,
    type: 'analyse',
    description: 'Diskursanalyse 2020-2026: to narrative poler (beredskap og kjoepekraft), manglende temaer (distribusjon i krise, importavhengighet, sirkularitet utover matsvinn). Kartlegger partilinjer og mediaframinger.',
    relevance: 'Grunnlag for hvitbokens narrative posisjonering — flytte rammet fra "billig mat" og "hoyere selvforsyningsprosent" til "trygg, rettferdig og robust matforsyning".',
  },
  {
    id: 'src-131',
    filename: 'alternative-distribusjonskanaler-norden-2026-04-20.md',
    title: 'Alternative distribusjonskanaler som utfordrer og kompletterer dagligvarekjedene i Norden',
    author: 'Food Research Process',
    year: 2026,
    type: 'analyse',
    description: 'REKO, D2C, subscription, kooperativer og digitale nisjer paa tvers av NO/SE/DK/FI. Penetrasjonsindeks, revenue-tall for Cheffelo (SEK 1,188 mrd), Aarstiderne (50k+ husstander), Matsmart (SEK 756m), Norsk lokalmat NOK 13,55 mrd.',
    relevance: 'Viser at alternative kanaler fyller strukturelle hull, ikke erstatter kjedene. Grunnlag for vurdering av policy-pakker for SMB-tilgang.',
  },
  {
    id: 'src-132',
    filename: 'nordisk-horeca-offentlige-maaltider-2026-04-20.md',
    title: 'Nordisk analyse av HORECA, offentlige maaltider og institusjonelle innkjoep',
    author: 'Food Research Process',
    year: 2026,
    type: 'analyse',
    description: '5,5 millioner offentlige maaltider daglig i Norden, med detaljert kartlegging av Sverige (3m/dag), Finland (850k elever), Danmark (Koebenhavn 70k/dag, 87,8% oekologisk), Norge (45% ungdomsskoler). Foodservice-grossist konsentrasjon: Kespro 49% FI.',
    relevance: 'Primaert grunnlag for loefteevaluering av HORECA og offentlige maaltider som struktur-motor for norsk matsystemomlegging.',
  },
  {
    id: 'src-133',
    filename: 'nordiske-dagligvarecase-mislyktes-2026-04-20.md',
    title: 'Nordiske dagligvarecase som mislyktes og hva de avslorer om etableringsbarrierer',
    author: 'Food Research Process',
    year: 2026,
    type: 'analyse',
    description: '7-dimensjonal etableringsbarrieremodell fra nordiske failures: Lidl NO (2008), ICA NO (2014), Mat.se/Mathem/Oda-rekonstruksjon (2024), Coop.dk MAD (2023), Stockmann Delicatessen (-EUR 11m 2016, solgt 2017), Irma (2023, 65 butikker splittet), Foodora FI (stengt 28. februar 2026).',
    relevance: 'Empirisk fundament for aa forstaa hvorfor nye aktoerer feiler; viser at online ikke bryter barrierer men flytter dem.',
  },
  {
    id: 'src-134',
    filename: 'nordiske-internasjonale-benchmarkcase-2026-04-20.md',
    title: 'Nordiske og internasjonale benchmark-case for matsystemomstilling',
    author: 'Food Research Process',
    year: 2026,
    type: 'analyse',
    description: '10 shortlistede benchmarks: Soer-Korea PAYT, Frankrike Garot-lov, TGTG, REKO, Plantefonden, Singapore novel foods, PeelPioneers, Agrain, Koebenhavns Madhus, Soedertaelje, Brasil PNAE, Arla FarmAhead. Syntese: demand+operational+finance-trekanten.',
    relevance: 'Benchmark-katalog med kvantifiserbare utfall for aa kalibrere norske ambisjoner og policy-design.',
  },
  {
    id: 'src-135',
    filename: 'norges-matrevolusjon-sirkular-innovasjon-2026-04-20.md',
    title: 'Norges matrevolusjon tar form langs kysten og i laben',
    author: 'Food Research Process (compass artifact)',
    year: 2026,
    type: 'analyse',
    description: 'Norsk sirkulaer-matinnovasjon: Greve Biogass (Den Magiske Fabrikken), Alginor ASA, Pelagia (Hordafor NOK 477m 2021), Biomega, Hofseth Biocare, Orkla Alternative Proteins (NOK 3 mrd maal 2025), Avisomo/Himmelgroent JV, Kolonihagen/Cultivate Food, CSA 80-90 gaarder 2024.',
    relevance: 'Kobler FS2026-agendaen til konkrete norske aktoerer og infrastruktur som alle er nyttet til etablerte verdikjeder.',
  },
  {
    id: 'src-136',
    filename: 'research-report-2026-04-20.pdf',
    title: 'Research Report — Food Research Process 2026-04-20 (samlet)',
    author: 'Food Research Process',
    year: 2026,
    type: 'rapport',
    description: 'Samlet PDF-bakgrunnsdokument som inneholder hovedresultater fra forskningsrunden 20. april 2026.',
    relevance: 'Referansedokument. Grundigere detaljer ligger i de 9 markdown-delrapportene.',
  },

  // ═══ Forskningsrunde 2026-04-20 — underliggende kilder sitert i dybderapportene ═══
  // Status trackes i research/evidence-pack/download-backlog-2026-04-20.csv
  // url_only = vi har lenken men ikke lokal PDF. downloaded = lokal fil i evidence-pack.

  {
    id: 'src-137',
    filename: 'norgesgruppen-registreringsdokument-2025.pdf',
    title: 'NorgesGruppen registreringsdokument 02.06.2025 (NO0013462705)',
    author: 'NorgesGruppen ASA',
    year: 2025,
    type: 'årsrapport',
    url: 'https://www.norgesgruppen.no/finans/',
    description: 'Primaerkilde for internleie NOK 120m (Johannson) + NOK 48m (Bjercke) 2024. Dokumenterer eiendomsgren-struktur.',
    relevance: 'Hovedgrunnlag for eiendomsmakt-analysen. Status: url_only — ikke lastet lokalt enda.',
  },
  {
    id: 'src-138',
    filename: 'reitan-eiendom-2024.pdf',
    title: 'Reitan Eiendom aarsrapport 2024',
    author: 'Reitan Eiendom AS',
    year: 2024,
    type: 'årsrapport',
    url: 'https://2024.reitaneiendom.no/',
    description: 'Dokumenterer ~2,077 millioner kvm bygningsmasse, NOK 2 mrd omsetning, og REBUS-overfoeringen desember 2023.',
    relevance: 'Primaerkilde for Reitans eiendomsportefoelje. Status: url_only — tilgjengelig som online-rapport.',
  },
  {
    id: 'src-139',
    filename: 'prop-33-l-2019-2020.pdf',
    title: 'Prop. 33 L (2019-2020) Lov om god handelsskikk',
    author: 'Regjeringen / Naerings- og fiskeridepartementet',
    year: 2020,
    type: 'lovverk',
    url: 'https://www.regjeringen.no/no/dokumenter/prop.-33-l-20192020/id2681097/',
    description: 'Lovforslaget som eksplisitt ikke regulerer buyer power, hylleavgifter eller forhandlingsmakt direkte.',
    relevance: 'Forklarer hvorfor dagens Lov om god handelsskikk er narrow-by-design. Status: url_only.',
  },
  {
    id: 'src-140',
    filename: 'prop-4-l-2025-2026.pdf',
    title: 'Prop. 4 L (2025-2026) Endringer i lov om god handelsskikk',
    author: 'Regjeringen / Naerings- og fiskeridepartementet',
    year: 2025,
    type: 'lovverk',
    url: 'https://www.regjeringen.no/no/dokumenter/prop.-4-l-20252026/id3124887/',
    description: 'Lovforslaget som flytter handheving til Konkurransetilsynet fra 30. april 2026 og styrker skriftlighetskrav.',
    relevance: 'Primaerkilde for overgangen DT -> KT. Status: url_only.',
  },
  {
    id: 'src-141',
    filename: 'konkurrensverket-2025-5-livsmedel.pdf',
    title: 'Konkurrensverket rapport 2025:5 - livsmedelsutredningen',
    author: 'Konkurrensverket',
    year: 2025,
    type: 'rapport',
    url: 'https://www.konkurrensverket.se/publikationer/',
    description: 'Svensk evaluering av livsmedelmarkedet med 4 sanksjonsavgifter per 31. oktober 2025.',
    relevance: 'Svensk nordisk komparativ for UTP-handheving. Status: url_only.',
    publisher: 'Konkurrensverket',
  },
  {
    id: 'src-142',
    filename: 'kfst-evaluering-foedevarehandelsloven-2024.pdf',
    title: 'KFST Evaluering af foedevarehandelsloven 2024',
    author: 'Konkurrence- og Forbrugerstyrelsen',
    year: 2024,
    type: 'rapport',
    url: 'https://en.kfst.dk/media/51101',
    description: '1 klage siden foedevarehandelsloven traadte i kraft, senere trukket. 0 vedtak.',
    relevance: 'Dansk nordisk komparativ for UTP-handheving. Status: url_only.',
    publisher: 'Konkurrence- og Forbrugerstyrelsen',
  },
  {
    id: 'src-143',
    filename: 'etmv-toimintakertomus-2024.pdf',
    title: 'Elintarvikemarkkinavaltuutettu toimintakertomus 2024',
    author: 'Ruokavirasto / Finnish Food Market Ombudsman',
    year: 2024,
    type: 'årsrapport',
    url: 'https://www.ruokavirasto.fi/globalassets/etmv/',
    description: '40% av frukt/baer-respondenter peker paa ensidige kontraktsendringer som stoerste problem. Drikkevare: betalingstid.',
    relevance: 'Finsk nordisk komparativ. Status: url_only (2023-versjon er nedlastet).',
    publisher: 'Ruokavirasto',
  },
  {
    id: 'src-144',
    filename: 'meld-st-25-2024-2025-sirkular.pdf',
    title: 'Meld. St. 25 (2024-2025) Handlingsplan for sirkulaer oekonomi',
    author: 'Regjeringen',
    year: 2025,
    type: 'lovverk',
    url: 'https://www.regjeringen.no/no/dokumenter/meld.-st.-25-20242025/id3095592/',
    description: 'Handlingsplan for sirkulaer oekonomi med kobling til matsvinn og verdikjeder.',
    relevance: 'Regulatorisk rammeverk for sirkularitet. Status: url_only.',
  },
  {
    id: 'src-145',
    filename: 'press-id3101561-2025.pdf',
    title: 'Regjeringen pressemelding id3101561 - konkurransepakke dagligvare (19. mai 2025)',
    author: 'Regjeringen / NFD',
    year: 2025,
    type: 'notat',
    url: 'https://www.regjeringen.no/id3101561/',
    description: 'Lansering av ny tiltakspakke for bedre konkurranse i dagligvaremarkedet.',
    relevance: 'Sentralt policy-event i regulatorisk tidslinje 2024-2026. Status: url_only.',
  },
  {
    id: 'src-146',
    filename: 'press-id3046671-2024.pdf',
    title: 'Regjeringen pressemelding id3046671 - beredskapslager matkorn (25. juni 2024)',
    author: 'Regjeringen / LMD',
    year: 2024,
    type: 'notat',
    url: 'https://www.regjeringen.no/id3046671/',
    description: 'Signering av nasjonale avtaler om beredskapslager for matkorn.',
    relevance: 'Sentralt policy-event i beredskapssporet. Status: url_only.',
  },
  {
    id: 'src-147',
    filename: 'lokalmatrapport-2025.pdf',
    title: 'Stiftelsen Norsk Mat - Lokalmatrapport 2025',
    author: 'Stiftelsen Norsk Mat',
    year: 2025,
    type: 'rapport',
    url: 'https://stiftelsennorskmat.no/',
    description: 'Norsk lokalmat 2025: NOK 13,55 mrd totalt, NOK 938m direkte salg, Bondens Marked NOK 76,4m.',
    relevance: 'Primaerkilde for alt-distribusjon-analysen. Status: url_only.',
    publisher: 'Stiftelsen Norsk Mat',
  },
  {
    id: 'src-148',
    filename: 'cheffelo-q4-2025.pdf',
    title: 'Cheffelo Q4 2025 investor release',
    author: 'Cheffelo AB',
    year: 2025,
    type: 'årsrapport',
    url: 'https://www.cheffelo.com/investors',
    description: 'Omsetning SEK 1,188 mrd 2025, ~17 millioner maaltider. 2024-fordeling: NO 505,5 MSEK / SE 403,1 MSEK / DK 149,6 MSEK.',
    relevance: 'Primaerkilde for D2C maaltidskasse-tall. Status: url_only.',
  },
  {
    id: 'src-149',
    filename: 'kbh-food-strategy-2019.pdf',
    title: 'Koebenhavn Food Strategy 2019',
    author: 'Koebenhavns Kommune',
    year: 2019,
    type: 'rapport',
    url: 'https://www.kk.dk/',
    description: 'Koebenhavns matstrategi — grunnlag for Madhus-modellen (87,8% oekologisk, 70k maaltider/dag).',
    relevance: 'Primaer HORECA-benchmark. Status: url_only.',
  },
  {
    id: 'src-150',
    filename: 'motiva-responsible-food-procurement-2026.pdf',
    title: 'Motiva - Guide for Responsible Procurement of Food (januar 2026)',
    author: 'Motiva Oy',
    year: 2026,
    type: 'rapport',
    url: 'https://www.motiva.fi/',
    description: 'Finsk nasjonal veileder for ansvarlig matinnkjoep i offentlig sektor.',
    relevance: 'Benchmark for operasjonalisering av 30%-klimavektsregelen. Status: url_only.',
    publisher: 'Motiva Oy',
  },
  {
    id: 'src-151',
    filename: 'plantefonden-projects-2025.pdf',
    title: 'Plantefonden projects 2023-2025',
    author: 'Plantefonden / Landbrugsstyrelsen',
    year: 2025,
    type: 'rapport',
    url: 'https://plantefonden.dk/',
    description: 'DKK 675m ramme, DKK 394m committed, 116 prosjekter 2023-2025.',
    relevance: 'Hovedkilde for Plantefonden-benchmark. Status: url_only.',
    publisher: 'Plantefonden',
  },
  {
    id: 'src-152',
    filename: 'arla-farmahead-2024.pdf',
    title: 'Arla FarmAhead Check sustainability data 2024',
    author: 'Arla Foods amba',
    year: 2024,
    type: 'årsrapport',
    url: 'https://www.arla.com/sustainability/',
    description: '8000 gaarder, 7 land, 99% melkedekning. EUR 337m utbetalt 2024. -9,9% CO2/kg melk fra 2020-basislinjen.',
    relevance: 'Hovedkilde for Arla-benchmark. Status: url_only.',
    publisher: 'Arla Foods',
  },
  {
    id: 'src-153',
    filename: 'evidence-pack/download-backlog-2026-04-20.csv',
    title: 'Download backlog for forskningsrunde 2026-04-20',
    author: 'Food Systems 2026',
    year: 2026,
    type: 'datasett',
    description: 'CSV-inventar over alle 89 underliggende kilder sitert i forskningsrunden 20. april 2026, med nedlastingsstatus og lokal sti.',
    relevance: 'Gir full kontroll over kildestatus: 19 nedlastet, 63 url_only, 7 metadata-only. Status trackes per kilde.',
  },
  {
    id: 'src-154',
    filename: 'mdpi-2071-1050-13-11-6231-turku-circular-food.pdf',
    title: 'Managing a Circular Food System in Sustainable Urban Farming. Experimental Research at the Turku University Campus (Finland)',
    author: 'Schönach et al.',
    year: 2021,
    type: 'forskning',
    url: 'https://www.mdpi.com/2071-1050/13/11/6231',
    doi: '10.3390/su13116231',
    publisher: 'MDPI Sustainability',
    description: 'Campusforsok ved Turku som reduserte plateavfall med 30 % gjennom kampanjer og kompostering av kjokkenavfall (7,5 m³/aar) til jordbruk.',
    relevance: 'Skalerbar nordisk case for sirkulaert matsystem paa institusjonelt niva.',
  },
  {
    id: 'src-155',
    filename: 'nested-circularity-finland-2023.pdf',
    title: 'Nested circularity in food systems: A Nordic case study on connecting biomass, nutrient and energy flows from field scale to continent',
    author: 'Kasper et al.',
    year: 2023,
    type: 'forskning',
    url: 'https://ui.adsabs.harvard.edu/abs/2021RCR...16405218K/abstract',
    publisher: 'Resources, Conservation and Recycling',
    description: 'Rammeverk for nested sirkularitet analysert paa tre finske landbruksregioner: husdyr dominerer naeringsflyt; internasjonal forhandel skaper ubalanse; biomasse og menneskelig avfall kan gi energi og lukke naeringslokken.',
    relevance: 'Metodisk rammeverk for a kvantifisere biomass/nutrient/energi-strommer i nordiske matsystemer.',
  },
  {
    id: 'src-156',
    filename: 'jcleprod-norwegian-seafood-sd-2025.pdf',
    title: 'System dynamics modeling of food loss and waste in the Norwegian seafood sector: Toward a circular economy',
    year: 2025,
    type: 'forskning',
    url: 'https://orbit.dtu.dk/en/publications/system-dynamics-modeling-of-food-loss-and-waste-in-the-norwegian-/',
    publisher: 'Journal of Cleaner Production',
    description: 'System-dynamikk-modell for den norske hvitfiskverdikjeden med scenarier for teknologi, forbrukeratferd og regulering.',
    relevance: 'Kvantitativ modellering som kan brukes i Natural State-scenarioanalyser for sirkulaer sjomat.',
  },
  {
    id: 'src-157',
    filename: 'frontiers-phosphorus-aquaculture-norway-2023.pdf',
    title: 'Circular economy for aquatic food systems: insights from a multiscale phosphorus flow analysis in Norway',
    year: 2023,
    type: 'forskning',
    url: 'https://www.frontiersin.org/journals/sustainable-food-systems/articles/10.3389/fsufs.2023.1248984/full',
    doi: '10.3389/fsufs.2023.1248984',
    publisher: 'Frontiers in Sustainable Food Systems',
    description: 'Fosforutslipp fra norsk akvakultur doblet 2005-2021; utnyttelsesgrad bare 19 %. Fytase, IMTA og slaminnsamling kan redusere utslipp, men lokal spredning risikerer akkumulering.',
    relevance: 'Forste multi-skala fosforanalyse av norsk oppdrett — sentralt for sirkulaer akvakultur-policy.',
  },
  {
    id: 'src-158',
    filename: 'ellen-macarthur-denmark-circular-2015.pdf',
    title: 'Delivering the Circular Economy: A Toolkit for Policymakers — Denmark case study',
    author: 'Ellen MacArthur Foundation',
    year: 2015,
    type: 'rapport',
    url: 'https://mst.dk/media/sexld3zc/potential-for-denmark-as-a-circular-economy-2015.pdf',
    publisher: 'Ellen MacArthur Foundation / Danish Business Authority',
    description: 'Rapport som viser at 56 % av husholdningers og 79 % av retail/horeca sitt matsvinn i Danmark er unngaaelig. Mulig besparelse €150-250m aarlig innen 2035.',
    relevance: 'Baseline-tall for dansk matsvinn og identifisert tiltakspotensial — kan brukes som nordisk benchmark.',
  },
  {
    id: 'src-159',
    filename: 'mst-denmark-food-waste-978-87-93529-80-9-2017.pdf',
    title: 'Food waste prevention in Denmark — LCA-based scenario analysis',
    author: 'Miljostyrelsen (Danish EPA)',
    year: 2017,
    type: 'rapport',
    url: 'https://www2.mst.dk/Udgiv/publications/2017/04/978-87-93529-80-9.pdf',
    publisher: 'Danish Environmental Protection Agency',
    description: 'LCA-basert kvantifisering av 716 000 tonn unngaaelig matsvinn i Danmark: husholdning 36 %, grossist/retail 23 %, prosess 19 %, primaer 14 %. Besparelse > 2 Mt CO2-ekv hvis halvert.',
    relevance: 'Offisiell dansk baseline for sektorfordelt matsvinn med metodegrunnlag.',
  },
  {
    id: 'src-160',
    filename: 'slu-eriksson-food-chain-sustainability-2016.pdf',
    title: 'Food chain sustainability in Sweden',
    author: 'Eriksson, M.',
    year: 2016,
    type: 'rapport',
    url: 'https://pub.epsilon.slu.se/13495/1/eriksson_m_160703.pdf',
    publisher: 'Swedish University of Agricultural Sciences (SLU)',
    description: 'Produktivitet og distribusjon har forbedret seg i svensk matverdikjede, men markedskonsentrasjon, ujevn forhandlingsstyrke og hoyt matsvinn bremser baerekraft. Etterlyser sirkulaer forskning.',
    relevance: 'Identifiserer forskningsgap og strukturelle barrierer i svensk matverdikjede.',
  },
  {
    id: 'src-161',
    filename: 'nordic-council-low-carbon-circular-transition-2022.pdf',
    title: 'Low-carbon circular transition in the Nordics — predictive management and digital platforms',
    author: 'Nordic Council of Ministers',
    year: 2022,
    type: 'rapport',
    url: 'https://norden.diva-portal.org/smash/get/diva2:1657847/FULLTEXT01',
    publisher: 'Nordic Council of Ministers',
    description: 'Syntese av 8 sirkulaer-muligheter i Norden. To gjelder mat: prediktiv styring for etterspurselsprognose/logistikk og digitale plattformer for matsvinnreduksjon.',
    relevance: 'Nordisk policy-baseline for digital sirkulaer matverdikjede.',
  },
  {
    id: 'src-162',
    filename: 'nordic-council-waste-prevention-nord2025-007.pdf',
    title: 'Effective waste prevention needs policies targeting the entire value chain',
    author: 'Nordic Council of Ministers',
    year: 2025,
    type: 'rapport',
    url: 'https://pub.norden.org/nord2025-007/nord2025-007.pdf',
    publisher: 'Nordic Council of Ministers',
    description: 'Policy-rapport som prioriterer avfallsforebygging fremfor resirkulering. Framhever Too Good To Go (NO) og ResQ (FI) som digitale plattformer mot matsvinn.',
    relevance: 'Direktiv fra Nordisk ministerraad om policy-miks for matsvinn-forebygging.',
  },
  {
    id: 'src-163',
    filename: 'iceland-ocean-cluster-seafood-circular-2022.pdf',
    title: 'Seafood in the Circular Economy — Analysis March 2022',
    author: 'Iceland Ocean Cluster',
    year: 2022,
    type: 'rapport',
    url: 'https://sjavarklasinn.is/wp-content/uploads/2022/03/Analysis-mar22-2.pdf',
    publisher: 'Iceland Ocean Cluster',
    description: '35-45 % av fisk spises typisk globalt; 100 % Fish-initiativet i Island naaet ~90 % utnyttelse via kollagen og biprodukter. Fem-trinns klynge-strategi beskrevet.',
    relevance: 'Referansecase for sirkulaer sjomat-klynge og dokumentasjon av 100 % Fish-initiativet.',
  },
  {
    id: 'src-164',
    filename: 'regjeringen-handlingsplan-sirkulaer-okonomi-2024-2025.pdf',
    title: 'Handlingsplan for en sirkulaer okonomi 2024-2025',
    author: 'Klima- og miljodepartementet',
    year: 2024,
    type: 'rapport',
    url: 'https://www.regjeringen.no/no/tema/klima-og-miljo/forurensning/innsiktsartikler/sirkular-okonomi/id2861732/',
    publisher: 'Klima- og miljodepartementet',
    description: 'Handlingsplan som understreker okt sirkulaer ressursutnyttelse i matverdikjeden og oppdatert regelverk for rest-raavarer.',
    relevance: 'Primaer norsk policy-ramme for sirkulaer mat 2024-2025.',
  },
  {
    id: 'src-165',
    filename: 'vision-2030-declaration.md',
    title: 'Our Vision 2030',
    author: 'Nordic prime ministers / Nordic Council of Ministers',
    year: 2019,
    type: 'strategi',
    url: 'https://www.norden.org/en/declaration/our-vision-2030',
    publisher: 'Nordic Council of Ministers',
    description: 'Politisk deklarasjon om at Norden skal bli verdens mest baerekraftige og integrerte region innen 2030, med prioritetene groent, konkurransedyktig og sosialt baerekraftig Norden.',
    relevance: 'Toppniva policyanker for aa koble Food Systems 2026 til Nordic Vision 2030.',
  },
  {
    id: 'src-166',
    filename: 'vision-2030-action-plan.md',
    title: 'Action Plan for Vision 2030',
    author: 'Nordic Council of Ministers',
    year: '2021-2024',
    type: 'strategi',
    url: 'https://www.norden.org/en/information/action-plan-vision-2030',
    publisher: 'Nordic Council of Ministers',
    description: 'Handlingsplan som operasjonaliserer Vision 2030 gjennom tre strategiske prioriteringer og 12 maal.',
    relevance: 'Gir maalstruktur for aa mappe Food Systems-data mot Vision 2030.',
  },
  {
    id: 'src-167',
    filename: 'vision-2030-indicators.md',
    title: 'Nordic Indicators for Our Vision 2030',
    author: 'Nordic Council of Ministers',
    year: 2021,
    type: 'rapport',
    url: 'https://www.norden.org/en/publication/nordic-indicators-our-vision-2030',
    publisher: 'Nordic Council of Ministers',
    description: 'Indikatorramme med 45 nordiske indikatorer fordelt paa groent, konkurransedyktig og sosialt baerekraftig Norden.',
    relevance: 'Primaer ramme for indikator-gap mellom NMRs Vision 2030 og Food Systems 2026.',
  },
  {
    id: 'src-168',
    filename: 'vision-2030-status-report-2023.md',
    title: 'The Nordic Region - a sustainable and integrated region? Our Vision 2030 Status Report 2023',
    author: 'Nordic Council of Ministers',
    year: 2023,
    type: 'rapport',
    url: 'https://www.norden.org/en/publication/nordic-region-sustainable-and-integrated-region-our-vision-2030-status-report-2023',
    publisher: 'Nordic Council of Ministers',
    description: 'Statusrapport for Vision 2030 basert paa indikatorrammen, med overordnet vurdering av framdrift mot et baerekraftig og integrert Norden.',
    relevance: 'Kontekstkilde for Vision 2030-status; bor suppleres med matsystemspesifikke prosjektdata.',
  },
  {
    id: 'src-169',
    filename: 'fjls-cooperation-programme-2025-2030.md',
    title: 'Nordic Co-operation Programme for Fisheries, Aquaculture, Agriculture, Food and Forestry 2025-2030',
    author: 'Nordic Council of Ministers',
    year: '2025-2030',
    type: 'rapport',
    url: 'https://pub.norden.org/politiknord2024-749/political-priorities.html',
    publisher: 'Nordic Council of Ministers',
    description: 'Samarbeidsprogram for fiskeri, akvakultur, jordbruk, mat og skogbruk som konkretiserer Vision 2030 for matsystemnaere sektorer.',
    relevance: 'Mest direkte NMR-kilde for aa koble Food Systems 2026 til Vision 2030 innen mat, biooekonomi, resiliens og ressursbruk.',
  },
  {
    id: 'src-170',
    filename: 'wur-elbersen-agri-residues-2022.pdf',
    title: 'Identifying and implementing circular applications of agri-residues',
    author: 'Wolter Elbersen, Anton Schultze-Jena, Siemen van Berkum, Just Dengerink, Maria Naranjo-Barrantes, Elisabeth Obeng',
    year: 2022,
    type: 'rapport',
    url: 'https://doi.org/10.18174/563389',
    doi: '10.18174/563389',
    publisher: 'Wageningen Food & Biobased Research',
    description: 'Wageningen-rapport som beskriver et circular evaluation framework for aa vurdere agri-residue applications etter circularity, socio-economic impact, environmental impact og implementability.',
    relevance: 'Sterk metodekilde for B-sidestream og C-adoption: hjelper TG-arbeidet aa skille teknisk ressursmulighet fra implementerbar, dokumenterbar sirkulaer anvendelse.',
  },
  {
    id: 'src-171',
    filename: 'kfst-salling-coop-afgoerelse-2025-03-26.pdf',
    title: 'Salling Group A/S erhvervelse af dele af Coop Danmark A/S',
    author: 'Konkurrenceradet',
    year: 2025,
    type: 'rapport',
    url: 'https://kfst.dk/media/edgjum43/20250326-salling-groups-erhvervelse-af-dele-af-coop-danmark-a.pdf',
    publisher: 'Konkurrence- og Forbrugerstyrelsen',
    description: 'Konkurrenceradsafgoerelse 2025-03-26: godkjenner Salling Groups erhvervelse av 33 dagligvarebutikker fra Coop Danmark, etter Fase II-utredning. To butikker (Taastrup og Slagelse) ble holdt utenfor pa grunn av lokale konkurransehensyn.',
    relevance: 'Primaerkilde for Spor C dansk dagligvare-adopsjon og markedsmakt: storste nordiske dagligvarefusjonen 2024-2025, gir KFST-merknader om lokal SSNIP-test, Fase II-process og remedier. Lukker DK adopsjon-gap i nordisk dekningsmatrise.',
  },
  {
    id: 'src-172',
    filename: 'kfst-ok-coop-afgoerelse-2024-06-26.md',
    title: 'OK a.m.b.a. erhvervelse af Coop Danmark A/S',
    author: 'Konkurrenceradet',
    year: 2024,
    type: 'rapport',
    url: 'https://kfst.dk/afgoerelser-ruling/konkurrenceomraadet/afgoerelser/2024/20240626-ok-coop-fusion',
    publisher: 'Konkurrence- og Forbrugerstyrelsen',
    description: 'Konkurrenceradet grep inn 2024-06-26 i OKs erhvervelse av Coop Danmark. Inngrepet utloeste salg av deler av Coop til Salling Group, og er den direkte foranledningen til 2025-avgjoerelsen (src-171).',
    relevance: 'Primaerkilde for forhistorien til Salling-Coop-fusjonen og dansk konkurransepolitisk handlingsrom i dagligvare. Sammen med src-171 dekker dette dagligvare-konsolideringen i DK 2024-2025.',
  },
  {
    id: 'src-173',
    filename: 'luke-food-balance-2024.md',
    title: 'Balance Sheet for Food Commodities 2024 (preliminary) and 2023 (final)',
    author: 'Luke / Natural Resources Institute Finland',
    year: 2025,
    type: 'statistikk',
    url: 'https://statdb.luke.fi/PxWeb/pxweb/en/LUKE/LUKE__maa__02%20Ravintotase',
    publisher: 'Natural Resources Institute Finland (Luke)',
    description: 'Finlands offisielle Food Balance Sheet 2024 (foreloepige tall) og 2023 (endelige tall), publisert 2025-06-17. Maaler innenlandsk produksjon, forbruk, lagerendringer, import og eksport per matkategori. Beregner per-capita-forbruk og fordeler innenlandsk bruk paa dyrefor, sad, industri og humant konsum.',
    relevance: 'Primaerkilde for FI selvforsyning og baseline-data for Spor A (fôr/import) og selvforsyningstema i nordisk komparativ analyse. Lukker FI selvforsyning-gap (0 docs) i dekningsmatrise. Statistikken flytter til Luonnonvaratieto-tjenesten i 2025.',
  },
  {
    id: 'src-174',
    filename: 'nesa-food-water-2030-programme.md',
    title: 'Food and Water 2030 Programme',
    author: 'Huoltovarmuuskeskus / National Emergency Supply Agency (NESA)',
    year: 2024,
    type: 'strategi',
    url: 'https://www.huoltovarmuuskeskus.fi/en/a/national-emergency-supply-agency-launches-new-food-and-water-2030-programme',
    publisher: 'Huoltovarmuuskeskus (NESA)',
    description: 'NESA-strategi 2027 inkluderer Food and Water 2030 som strategisk satsingsomraade. Programmet skal sikre at Finland kan produsere mat og opprettholde matproduksjon i langvarige krisesituasjoner, med klimaendring og forsyningskrise som drivere. Lansert april 2024.',
    relevance: 'Primaerkilde for Finlands nordisk-ledende posisjon innen matsikkerhet og beredskap. Lukker FI selvforsyning/beredskap-gap (0 docs) i dekningsmatrise. Relevant for Spor C som adopsjons-/governance-mekanisme og for nordisk beredskapssammenligning.',
  },
  {
    id: 'src-175',
    filename: 'slu-karimi-filamentous-fungi-vinasse-2019.pdf',
    title: 'Evaluation of Filamentous Fungal Biomass Cultivated on Vinasse as an Alternative Nutrient Source of Fish Feed',
    author: 'Karimi et al.',
    year: 2019,
    type: 'forskning',
    url: 'https://pub.epsilon.slu.se/16481/1/karimi_et_al_200127.pdf',
    publisher: 'Sveriges lantbruksuniversitet (SLU)',
    doi: '10.3390/fermentation5040099',
    description: 'SLU/Karimi et al. (2019) evaluerer filamentoes soppbiomasse dyrket paa vinasse (biproduct fra bioetanolproduksjon) som alternativ proteinkilde i fiskefôr. Del av SLUs "Framtidens foder bygger paa kretslopp"-prosjekt under prof. Anders Kiessling.',
    relevance: 'Primaerkilde for Spor A sirkulaert foer i SE: dokumenterer mikrobiell protein fra sidestroem som FoU-spor. Lukker SE sirkulaert foer-gap (0 docs) i dekningsmatrise. Komplementerer NMBU/Foods of Norway-evidens i CL-A-001/A-002.',
  },
  {
    id: 'src-176',
    filename: 'jordbruksverket-livsmedelsstrategi-rapport-2024-3.pdf',
    title: 'Uppfoeljning och utvaerdering av livsmedelsstrategin - Rapport 2024:3',
    author: 'Jordbruksverket',
    year: 2024,
    type: 'rapport',
    url: 'https://www2.jordbruksverket.se/download/18.41aa6e2218e54b01de91a5f9/1711375515932/ra24_3.pdf',
    publisher: 'Jordbruksverket',
    description: 'Aarsrapport 2024 paa Sveriges livsmedelsstrategi: 6 kapitler og 12 vedlegg som folger verdikjedens utvikling fra 2016 og fremover. Daekker produksjon, baerekraftig produksjonsmetoder, foer/biomasse og miljopaaverkning.',
    relevance: 'Primaerkilde for SE adopsjon-/policy-spor (Spor C) og baseline for svensk livsmedelsstrategi. Komplementerer norsk Matsvinnutvalget og dansk KFST-evidens; gir nordisk policy-sammenligningsgrunnlag.',
  },
]
