import type { EvidenceAppraisalReviewManifest } from '../../src/lib/citations/evidence-appraisal-review-workflow'

// Human-review template only. All substantive fields intentionally remain
// blank. The workflow refuses even a dry-run database inspection until every
// entry has a complete named-human disposition and the exact PDF bytes are
// present at reviewArtifactPath with expectedSourceHash.
//
// Every entry points to a durable evidence-pack destination and an exact hash.
// A local artifact is not human-review evidence by itself: the reviewer must
// read the pinned bytes at that path and complete the named-human disposition.
export const EVIDENCE_APPRAISAL_PILOT_REVIEW_MANIFEST = {
  manifestVersion: 1,
  workflowId: 'evidence-appraisal-pilot-v1',
  entries: [
    {
      appraisalId: 'evidence_appraisal_src_30_v1',
      targetKind: 'SourceDoc',
      targetId: 'src-30',
      reviewBasisCitationId: 'academic_anchor_src30_energy_p25_v1',
      reviewLocator: 'https://asko.no/globalassets/om-asko/miljo/barekraft-i-asko-2024.pdf',
      reviewArtifactPath: 'research/evidence-pack/arsrapporter/asko-barekraft-2024.pdf',
      expectedSourceHash: '94b68068c89e9713e968f3c5ef17ed0f4e74fa57206ea5dd383aac6b44529108',
      hashAlgorithm: 'sha256',
      reviewState: 'pending_human_review',
      attestation: null,
      status: null,
      basis: null,
      studyDesign: null,
      studyDesignDetails: null,
      methodologySummary: null,
      sampleOrCoverage: null,
      applicability: null,
      applicabilityContext: null,
      applicabilityNotes: null,
      limitationsStatus: null,
      limitations: [],
      limitationsNotes: null,
      riskOfBias: null,
      riskOfBiasNotes: null,
      framework: null,
      frameworkVersion: null,
      reviewMethod: null,
      reviewedSourceHash: null,
      reviewedBy: null,
      reviewedAt: null,
      notApplicableReason: null,
      notes: null,
    },
    {
      appraisalId: 'evidence_appraisal_src_32_v1',
      targetKind: 'SourceDoc',
      targetId: 'src-32',
      reviewBasisCitationId: 'academic_anchor_src32_reduction_p2_v1',
      reviewLocator: 'https://norsus.no/wp-content/uploads/7.-OR.27.25-Faktark-om-matsvinn-i-Norge-2024-1.pdf',
      reviewArtifactPath: 'research/evidence-pack/forskningsinstitutt/norsus-matsvinn-2024.pdf',
      expectedSourceHash: '39523279d3afff6f0f41b5baea04590f2ce6499f2a2518a04fa82b29395c7fcf',
      hashAlgorithm: 'sha256',
      reviewState: 'pending_human_review',
      attestation: null,
      status: null,
      basis: null,
      studyDesign: null,
      studyDesignDetails: null,
      methodologySummary: null,
      sampleOrCoverage: null,
      applicability: null,
      applicabilityContext: null,
      applicabilityNotes: null,
      limitationsStatus: null,
      limitations: [],
      limitationsNotes: null,
      riskOfBias: null,
      riskOfBiasNotes: null,
      framework: null,
      frameworkVersion: null,
      reviewMethod: null,
      reviewedSourceHash: null,
      reviewedBy: null,
      reviewedAt: null,
      notApplicableReason: null,
      notes: null,
    },
    {
      appraisalId: 'evidence_appraisal_src_45_v1',
      targetKind: 'SourceDoc',
      targetId: 'src-45',
      reviewBasisCitationId: 'academic_anchor_src45_commissioner_p2_v1',
      reviewLocator: 'https://osloeconomics.no/wp-content/uploads/2024/06/Oslo-Economics-Konkurransen-i-dagligvaremarkedet-betydelig-bedre-enn-sitt-rykte.pdf',
      reviewArtifactPath: 'research/evidence-pack/konsulentrapport/oslo-economics-forsvar-2024.pdf',
      expectedSourceHash: '6155c0f06fea09224f3ec235453af91641aa99302493d97faad0f0c772ccc8de',
      hashAlgorithm: 'sha256',
      reviewState: 'pending_human_review',
      attestation: null,
      status: null,
      basis: null,
      studyDesign: null,
      studyDesignDetails: null,
      methodologySummary: null,
      sampleOrCoverage: null,
      applicability: null,
      applicabilityContext: null,
      applicabilityNotes: null,
      limitationsStatus: null,
      limitations: [],
      limitationsNotes: null,
      riskOfBias: null,
      riskOfBiasNotes: null,
      framework: null,
      frameworkVersion: null,
      reviewMethod: null,
      reviewedSourceHash: null,
      reviewedBy: null,
      reviewedAt: null,
      notApplicableReason: null,
      notes: null,
    },
  ],
} as const satisfies EvidenceAppraisalReviewManifest
