#!/usr/bin/env python3
"""Append corrected candidate returns; default verifies deterministic generated bytes.
No database writes, human review, coverage promotion, contact or publishing.
Existing frozen return files are inputs only. Use --write once for the new run.
"""
import copy,hashlib,json,pathlib,sys
HERE=pathlib.Path(__file__).resolve().parent
ROOT=HERE.parents[3]
BASE=pathlib.Path('docs/project/analysis/source-review-beredskap-2026-09-09')
RUN=BASE/'research-runs/20260909-beredskap-wave1'
PRIVATE=pathlib.Path('/Users/gabrielfreeman/.codex/visualizations/2026/09/09/01a0862f-bd95-7660-802d-282c781c1c5f/status-restlist/corrections-001')
ORIGINAL_ROOT='/Users/gabrielfreeman/.codex/worktrees/a4f5/Food Systems 2026/'
STAMP='2026-09-09'
ROUND2='--round2' in sys.argv
ORDER=['B19','B20'] if ROUND2 else ['B04','B08','B13','B14','B09','B20']
SUFFIX='002' if ROUND2 else '001'
sha=lambda b:hashlib.sha256(b).hexdigest()
def encoded(x):return (json.dumps(x,ensure_ascii=False,indent=2)+'\n').encode()
def canonical(x):return sha(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode())
def actual(p):
 p=pathlib.Path(p)
 return p if p.is_absolute() else ROOT/p
def read(p):return actual(p).read_bytes()
def jread(p):return json.loads(read(p))
planned={};replacements={};checks=[]
def output(p,x):planned[str(p)]=x if isinstance(x,bytes) else encoded(x)
def content(p):return planned[str(p)] if str(p) in planned else read(p)
def digest(p):return sha(content(p))
def replace(x):
 if isinstance(x,str):return replacements.get(x,x)
 if isinstance(x,list):return [replace(v) for v in x]
 if isinstance(x,dict):return {k:replace(v) for k,v in x.items()}
 return x
def mapfile(old,new):
 replacements[str(old)]=str(new);replacements[ORIGINAL_ROOT+str(old)]=str(new)
 replacements[sha(read(old))]=digest(new)
def source(sid,title,raw,txt,url,publisher,locs):
 return {'schema':'beredskap-source/v1','templateOnly':False,'sourceId':sid,'title':title,'publisher':publisher,'url':url,'documentVersion':'retained original bytes','publishedAt':None,'accessedAt':STAMP,'readScope':'Existing raw bytes and stated locators rechecked for correction; acquisition remains historical.','sourceRole':'primary_binding_correction','accessStatus':'retained_bytes_hash_verified','rights':{'internalUseBasis':'internal_source_validation','redistributionAllowed':False},'rawPath':str(raw),'rawSha256':sha(read(raw)),'extractedTextPath':str(txt),'extractedTextSha256':sha(read(txt)),'exactLocators':locs,'limitations':['Candidate-only correction; no new survey data or human authority.']}
intake_path=RUN/('M-ASTRA/master-intake-corrections-001.json' if ROUND2 else 'M-ASTRA/master-intake.json');intake=jread(intake_path)
originals={w['packageId']:w for w in intake['workerReturns']}
changed=[]
for b in ORDER:
 old=pathlib.Path(originals[b]['handoffPath']).parent;new=RUN/b/(b+'-20260909-correction-'+('002' if ROUND2 and b=='B20' else '001'))
 original_h=jread(old/'handoff.json');h=replace(copy.deepcopy(original_h));rid=new.name
 docs={n:replace(jread(old/n)) for n in ['sources.json','observations.json','gaps.json','search-log.json']}
 for d in docs.values():
  d['runId']=rid
  d['correctionProvenance']={'previousRunId':original_h['runId'],'previousHandoffPath':str(old/'handoff.json'),'previousHandoffSha256':sha(read(old/'handoff.json')),'newPrimaryAcquisition':False,'human_verified':False}
 sources=docs['sources.json']['sources'];claims=docs['observations.json']['observations'];cs={c['candidateId']:c for c in claims}
 notes=[]
 if b=='B04':
  for loc,lo,hi in zip(cs['B04-C04']['evidencePayload']['sourceBindings'],[512,1403],[545,1412]):
   loc['exactLocator'].update(pathHint='rapport-2023-full.txt',start=lo,end=hi)
   s=next(s for s in sources if s['sourceId']=='B04-S007')
   selected=('\n'.join(read(s['extractedTextPath']).decode().splitlines()[lo-1:hi])+'\n').encode()
   assert sha(selected)==loc['locatorEvidenceSha256']
  s['exactLocators']=[v['exactLocator'] for v in cs['B04-C04']['evidencePayload']['sourceBindings']]
  notes=['B04-C04: subset line numbers replaced by fulltext 512–545 and 1403–1412. Selected passage hashes are unchanged.']
 if b=='B08':
  root=pathlib.Path('/Users/gabrielfreeman/.codex/visualizations/2026/09/09/01a084fe-a36c-7fb1-86c2-4387109e3c36/round-004')
  spec=[('R4-NO-S003','SSB Korn og oljevekster: method',root/'norway/method.html',root/'norway/method.txt','https://www.ssb.no/jord-skog-jakt-og-fiskeri/jordbruk/statistikk/korn-og-oljevekster-areal-og-avlinger','SSB'),('METH-S09','SCB SkordarL2 retained 48-cell slice',root/'method/scb-slice.json',root/'method/scb-slice.json',None,'SCB'),('DKFI-S002','DST HST data response',root/'dk-fi/DK-data.csv',root/'dk-fi/DK-data.csv','https://api.statbank.dk/v1/data','Danmarks Statistik')]
  for sid,title,raw,txt,url,pub in spec:
   bindings=[v for c in claims for v in c['evidencePayload']['sourceBindings'] if v['sourceId']==sid]
   s=source(sid,title,raw,txt,url,pub,[v['exactLocator'] for v in bindings])
   assert bindings and all(v['rawSha256']==s['rawSha256'] and v['extractedTextSha256']==s['extractedTextSha256'] for v in bindings)
   sources.append(s)
  cs['B08-C02']['claim']=cs['B08-C02']['claim'].replace('Production-weighted P/A','Aggregate P/A (equivalently, area-weighted component yield)')
  assert abs((2984800+315600)/(394450+63100)-cs['B08-C02']['value']['PA_t_ha'])<1e-12
  notes=['Three existing primary sources are explicitly registered for B08-C01–C04. No replacement raw bytes.','B08-C02: aggregate P/A is area-weighted component yield; values and reported Eurostat 7.22 remain distinct and unchanged.']
 if b=='B13':
  s=next(s for s in sources if s['sourceId']=='B13-S001')
  loc={'type':'pdf_pages','start':13,'end':13,'printedPage':11,'label':'Tabell 2-1; physical PDF page 13, printed page 11'}
  table=source('B13-S001-TABLE21',s['title']+' — Tabell 2-1',s['rawPath'],PRIVATE/'sifo-physical-page-13.txt',s['url'],s['publisher'],[loc])
  sources.append(table)
  s['readScope']=s['readScope'].replace('Tabell 2-1 (PDF pp.11–12)','Tabell 2-1 (physical PDF p.13, printed p.11)')
  s['exactLocators'][0]=loc
  binding=cs['B13-C02']['evidencePayload']['sourceBindings'][0]
  binding.update(sourceId=table['sourceId'],extractedTextSha256=table['extractedTextSha256'],exactLocator=loc)
  notes=['B13-C02: Tabell 2-1 is physical PDF page 13 / printed page 11. New pdftotext page extract verified visually; total survey Ns unchanged; subgroup Ns remain missing.']
 if b in ['B14','B20']:
  found=0
  for inp in h['inputs']:
   if actual(inp['path']).is_dir():
    name='raw-manifest.json' if b=='B14' else 'synthesis-notes.json'
    p=pathlib.Path(inp['path'])/name
    assert sha(read(p))==inp['sha256']
    inp['path']=str(p);inp['note']='Exact file path corrected from historical directory pointer; original expected bytes unchanged.';found+=1
  assert found==(0 if ROUND2 and b=='B20' else 1)
  if not found:name='synthesis-notes.json (exact file retained from preceding correction)'
  notes.append('Input directory pointer replaced by exact '+name+' matching the original expected SHA.')
 if b=='B19':
  gap=next(g for g in docs['gaps.json']['gaps'] if g['gapId'].endswith('-G03'))
  assert gap['originalGapId']=='FS-03'
  gap['originalGapId']=None;gap['overlapWithGapIds']=[x for x in gap['overlapWithGapIds'] if x!='FS-03']
  gap['referenceCorrection']={'previousOriginalGapId':'FS-03','reason':'FS-03 concerns estimated food waste versus measured collection flows, not model attestation. Historical record preserved; this attestation gap stands independently.','semanticGapClosed':False}
  notes=['B19 G03: removed incorrect FS-03 parent/overlap; gap identity and missing model attestation remain. FS-03 retains its original food-waste meaning.']
 if b=='B09':notes=['Dependency B08 is rebound to its corrected return. Existing scientific claims and open gaps are retained; new hashes require fresh review.']
 if b=='B20':
  old_manifest=pathlib.Path(next(s for s in sources if s['sourceId']=='B20-S11')['rawPath'])
  manifest=replace(jread(old_manifest));manifest['correctionOf']={'path':str(old_manifest),'sha256':sha(read(old_manifest))}
  p=new/'dependency-handoffs-B01-B19.json';output(p,manifest);mapfile(old_manifest,p)
  docs={k:replace(v) for k,v in docs.items()};h=replace(h)
  sources=docs['sources.json']['sources'];claims=docs['observations.json']['observations'];cs={c['candidateId']:c for c in claims}
  coverage=jread(BASE/'research-plan/coverage.json')['gaps']
  bindings=cs['B20-C12']['evidencePayload']['sourceBindings'];oldbind=copy.deepcopy(next(v for v in bindings if v['sourceId']=='B20-S06'))
  bindings[:]=[v for v in bindings if v['sourceId']!='B20-S06']
  for gid in ['CLIM-G03','R4-G004','R5-G10']:
   index=next(i for i,g in enumerate(coverage) if g['id']==gid)
   v=copy.deepcopy(oldbind);v['exactLocator']={'type':'json_path','path':'/gaps/'+str(index),'label':gid};bindings.append(v)
  notes+=['B20-C12: three valid JSON array pointers replace a pipe-separated non-pointer.','B01–B19 dependency register rehashed; updated B04/B08/B09/B13/B14 returns included. No C1–C5 effect or semantic gap closure inferred.']
 # Resolve filename-only profile paths to the already preserved exact original profile.
 for c in claims:
  c['runId']=rid
  if not actual(c['targetProfilePath']).is_file():
   p=old/c['targetProfilePath']
   if not actual(p).is_file():p=pathlib.Path(original_h['privateArtifactRoot'])/c['targetProfilePath']
   assert sha(read(p))==c['targetProfileSha256'];c['targetProfilePath']=str(p)
  assert sha(read(c['policyPath']))==c['policySha256']
  assert sha(read(c['targetProfilePath']))==c['targetProfileSha256']
  c['evidenceSha256']=canonical(c['evidencePayload']);c.pop('candidateSha256',None);c['candidateSha256']=canonical(c)
  assert c['human_verified'] is False
 for s in sources:
  for pk,hk in [('rawPath','rawSha256'),('extractedTextPath','extractedTextSha256')]:
   if s.get(pk) and s.get(hk):assert digest(s[pk])==s[hk],(b,s['sourceId'],pk)
 findings=read(old/'findings.md').decode()
 if b=='B08':findings=findings.replace('Production-weighted P/A','Aggregate P/A (area-weighted component yield)').replace('production-weighted','area-weighted')
 if b=='B13':findings=findings.replace('PDF pp.11–12','physical PDF p.13 / printed p.11')
 findings='# Korrigert kandidatretur '+rid+'\n\n'+ '\n'.join('- '+n for n in notes)+'\n\nResten av den historiske fagteksten er videreført fra '+original_h['runId']+'. Dette er ingen ny datainnhenting eller menneskelig godkjenning.\n\n'+findings
 output(new/'findings.md',findings.encode())
 for name,d in docs.items():output(new/name,d)
 provenance={'schema':'beredskap-correction/v1','packageId':b,'runId':rid,'previousHandoffPath':str(old/'handoff.json'),'previousHandoffSha256':sha(read(old/'handoff.json')),'corrections':notes,'reviewRequiredForChangedHashes':True,'previousReviewInherited':False,'model':{'requestedModel':None,'attestedModel':None,'role':'coordinator correction; original research and new review separately attributed'},'human_verified':False,'canonicalChanges':False,'readinessChanged':False,'published':False}
 output(new/'correction.json',provenance)
 verification={'schema':'beredskap-verification/v1','runId':rid,'checkedAt':STAMP,'scope':'Deterministic correction, direct source-file bytes, policy/target hashes, candidate/evidence hashes and dependencies. Scientific review is separate.','checks':[{'id':'corrected-bindings-and-hashes','result':'passed','candidateCount':len(claims)},{'id':'direct-source-files','result':'passed','sourceCount':len(sources)}],'failures':[],'notPerformed':['new primary acquisition','full original research repeated by coordinator','human review','canonical import','CI','deployment','authenticated UI'],'human_verified':False,'astraReviewExecuted':False,'ciVerified':False,'deploymentVerified':False}
 output(new/'verification.json',verification)
 for name in ['findings.md',*docs,'verification.json']:
  mapfile(old/name,new/name)
 h.update(runId=rid,createdAt=STAMP,worktreePath=str(ROOT),headCommit='87d7516',model=provenance['model'],correctionOf=provenance,astraReviewExecuted=False)
 h['inputs'].append({'path':str(old/'handoff.json'),'sha256':sha(read(old/'handoff.json')),'private':False,'accessRequired':False,'role':'immutable historical return'})
 # Historical git evidence is not evidence for this correction run.
 for k in ['gitStatusEvidencePath','gitStatusSha256']:h.pop(k,None)
 h['files']=[{'path':str(p),'sha256':digest(p),'private':False} for p in sorted(pathlib.Path(p) for p in planned if pathlib.Path(p).parent==new)]
 for dep in h['dependencies']:assert digest(dep['handoffPath'])==dep['handoffSha256']
 for inp in h['inputs']:
  if not actual(inp['path']).is_file() and inp['path'] not in planned and actual(old/inp['path']).is_file():inp['path']=str(old/inp['path'])
  assert digest(inp['path'])==inp['sha256'],(b,inp)
 output(new/'handoff.json',h);mapfile(old/'handoff.json',new/'handoff.json')
 replacements[original_h['runId']]=rid
 changed.append({'packageId':b,'previousRunId':original_h['runId'],'runId':rid,'handoffPath':str(new/'handoff.json'),'handoffSha256':digest(new/'handoff.json'),'candidateCount':len(claims),'corrections':notes})
# New intake; frozen historical gap overlays and original research remain explicit.
m=copy.deepcopy(intake)
m.update(intakeId='master-intake-20260909-corrections-'+SUFFIX,frozenAt=STAMP,previousIntakeSha256=sha(read(intake_path)),previousIntakePath=str(intake_path),freezeRevision=intake['freezeRevision']+1,frozenBy='coordinator correction builder',freezeNote='New intake for corrected/rebound worker returns; preceding intake remains immutable. Requires separate Astra review.',correctionRuns=changed)
if not ROUND2:m['freezeNote']='New intake for six corrected/rebound worker returns; original intake remains immutable. Requires separate Astra review.'
if ROUND2:
 m['inheritedCorrectionRuns']=intake['correctionRuns']
 m['gapReferenceCorrections']=[{'packageId':'B19','gapId':'B19-B19-20260909T103719Z-dd7b5e44-G03','previousOriginalGapId':'FS-03','currentOriginalGapId':None,'reason':'Model attestation is an independent gap; FS-03 remains estimated waste versus measured collection.'}]
 m['historicalGapInventoryRetained']=True
for w in m['workerReturns']:
 if w['packageId'] in ORDER:
  ch=next(c for c in changed if c['packageId']==w['packageId']);h=json.loads(content(ch['handoffPath']))
  w.update(runId=ch['runId'],handoffPath=ch['handoffPath'],handoffSha256=ch['handoffSha256'],fileManifest=h['files'])
for c in m['candidateInventory']:
 if c['packageId'] in ORDER:
  ch=next(x for x in changed if x['packageId']==c['packageId'])
  obs=json.loads(content(pathlib.Path(ch['handoffPath']).parent/'observations.json'))['observations'];v=next(x for x in obs if x['candidateId']==c['candidateId'])
  for k in ['runId','candidateSha256','evidenceSha256']:c[k]=v[k]
m['historicalGapOverlayNote']='Gap inventory remains the immutable 92-reference historical overlay; no semantic gap closure. New return gap IDs retain historical identity.'
m['b20AdditionalDeliveryFiles']=replace(m['b20AdditionalDeliveryFiles'])
new_intake=RUN/('M-ASTRA/master-intake-corrections-'+SUFFIX+'.json')
output(new_intake,m)
output(HERE.relative_to(ROOT)/('correction-index-002.json' if ROUND2 else 'correction-index.json'),{'schema':'beredskap-corrections-index/v1','originalIntakeSha256':sha(read(intake_path)),'newIntakePath':str(new_intake),'newIntakeSha256':digest(new_intake),'runs':changed,'human_verified':False,'semanticGapClosed':False})
for p,data in planned.items():
 dest=ROOT/p
 if '--write' in sys.argv:
  if dest.exists():assert dest.read_bytes()==data, 'Refuse to overwrite existing different bytes: '+p
  else:dest.parent.mkdir(parents=True,exist_ok=True);dest.write_bytes(data)
 else:assert dest.read_bytes()==data,'Generated drift: '+p
print(json.dumps({'generatedFiles':len(planned),'correctedPackages':ORDER,'rehashedCandidates':sum(c['candidateCount'] for c in changed),'intakeCandidates':len(m['candidateInventory']),'historicalGapReferences':len(m['gapInventory']),'write':'--write' in sys.argv,'checks':'passed'}))
